workflows:
  unity-ios:
    name: Unity iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.halbus.labedu # MUDE AQUI
      vars:
        UNITY_VERSION: 2022.3.62f1
        BUNDLE_ID: com.halbus.labedu # MUDE AQUI
        APP_NAME: Bioblocks # MUDE AQUI
      groups:
        - unity_credentials
        - app_store_credentials
      xcode: latest
      node: latest

    cache:
      cache_paths:
        - $HOME/Library/Unity/cache
        - Library

    scripts:
      - name: Create Export Options
        script: |
          cat > /tmp/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>\$APP_STORE_CONNECT_ISSUER_ID</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF

      - name: Activate Unity License (Personal)
        script: |
          unity-editor \
            -batchmode \
            -quit \
            -nographics \
            -logFile \
            -createManualActivationFile || true
          
          unity-editor \
            -batchmode \
            -quit \
            -nographics \
            -logFile \
            -username "$UNITY_EMAIL" \
            -password "$UNITY_PASSWORD" || true

      - name: Build Unity iOS Project
        script: |
          unity-editor \
            -batchmode \
            -quit \
            -nographics \
            -projectPath . \
            -buildTarget iOS \
            -executeMethod BuildScript.BuildiOS \
            -logFile unity-build.log
          
          ls -la build/ios/

      - name: Build iOS App with Xcode
        script: |
          cd build/ios
          
          sed -i '' 's/PRODUCT_BUNDLE_IDENTIFIER = .*/PRODUCT_BUNDLE_IDENTIFIER = '$BUNDLE_ID';/' Unity-iPhone.xcodeproj/project.pbxproj
          
          xcode-project build-ipa \
            --workspace Unity-iPhone.xcworkspace \
            --scheme Unity-iPhone \
            --archive-flags="-destination 'generic/platform=iOS'" \
            --export-options-plist /tmp/export_options.plist

    artifacts:
      - build/ios/build/**/*.ipa
      - unity-build.log