using System.Collections.Generic;
using QuestionSystem;

public class BiochemistryIntroductionQuestionDatabase : IQuestionDatabase
{
    private bool databaseInDevelopment = false;

    private List<Question> questions = new List<Question>
    {
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "São características de sistemas vivos, exceto:",
            answers = new string[] {
                "Utilizar a energia do ambiente",
                "Possuir organização microcópica.",
                "Capacidade de se autoreplicar",
                "Não respondem as alterações do ambiente"
            },
            correctIndex = 3,
            questionNumber = 1,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_001",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual a teoria que afirmava que os seres vivos possuíam uma força vital?",
            answers = new string[] {
                "Teoria da abiogênese",
                "Teoria da biogênese",
                "Vitalismo",
                "Teoria celular"
            },
            correctIndex = 2,
            questionNumber = 2,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_002",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual fato mais contribuiu para a perda de credibilidade da doutrina do vitalismo?",
            answers = new string[] {
                "A criação da tabela periódica dos elementos",
                "O fim da crença na geração espontânea dos seres vivos",
                "O desenvolvimento da teoria atómica dos elementos",
                "A lei da conservação das massas"
            },
            correctIndex = 1,
            questionNumber = 3,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_003",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual a importância de Louis Pasteur para o desenvolvimento da Bioquímica?",
            answers = new string[] {
                "Pasteur contribuiu para demonstrar que a vida surgia espontaneamente.",
                "Pasteur estabeleceu a relação entre microorganismos e doenças, desafiando a geração espontânea.",
                "Pasteur desenvolveu métodos de esterilização de alimentos por luz ultravioleta.",
                "Pasteur foi o primeiro a descobrir o DNA como material genético."
            },
            correctIndex = 1,
            questionNumber = 4,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_004",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Quais os quatro elementos mais abundantes nos organismos vivos?",
            answers = new string[] { 
                "H, O, N, C", 
                "C, H, O, P", 
                "C, N, O, S", 
                "H, O, P, S" 
                },
            correctIndex = 0,
            questionNumber = 5,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_005",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Os seres vivos são caracterizados por um alto grau de complexidade química e organização molecular. Qual apção melhor se alinha com essa afirmação?",
            answers = new string[] {
                "Os seres vivos são formados por moléculas simples, sem organização interna definida",
                "Os seres vivos apresentam moléculas complexas, como proteínas e lipídios",
                "Os seres vivos não dependem de reações químicas para manter suas funções vitais",
                "Os seres vivos possuem apenas substâncias inorgânicas em sua composição química"
            },
            correctIndex = 1,
            questionNumber = 6,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_006",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual é a importância dos grupos funcionais nas moléculas orgânicas que formam macromoléculas?",
            answers = new string[] {
                "Definem propriedades e reações das moléculas",
                "Tornam todas as moléculas iguais.",
                "Existem apenas em moléculas inorgânicas.",
                "Impedem a formação de macromoléculas."
            },
            correctIndex = 0,
            questionNumber = 7,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_007",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Identifique a estrutura que representa um hidrocarboneto ramificado",
            answers = new string[] {
                "AnswerImages/IntroductionDB/benzeno",
                "AnswerImages/IntroductionDB/2-butanol",
                "AnswerImages/IntroductionDB/2-3-dimetil-pentano",
                "AnswerImages/IntroductionDB/propanamina"
            },
            correctIndex = 2,
            questionNumber = 8,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_008",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Identifique a estrutura molecular do ácido carboxílico",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-butanona",
                "AnswerImages/IntroductionDB/metanoato-de-propila",
                "AnswerImages/IntroductionDB/propanal",
                "AnswerImages/IntroductionDB/acido-propanoico"
            },
            correctIndex = 3,
            questionNumber = 9,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_009",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Identifique a estrutura molecular da amina",
            answers = new string[] {
                "AnswerImages/IntroductionDB/n-trimetil-etanamina",
                "AnswerImages/IntroductionDB/propanamida",
                "AnswerImages/IntroductionDB/trans-3-hexeno",
                "AnswerImages/IntroductionDB/fenol"
            },
            correctIndex = 0,
            questionNumber = 10,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_010",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/haxano",
                "AnswerImages/IntroductionDB/ciclo-hexano",
                "AnswerImages/IntroductionDB/benzeno",
                "AnswerImages/IntroductionDB/3-metil-haxano"
            },
            correctIndex = 1,
            questionNumber = 11,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer11",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_011",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-metil-3-dimetil-pentano",
                "AnswerImages/IntroductionDB/ciclo-hexano",
                "AnswerImages/IntroductionDB/benzeno",
                "AnswerImages/IntroductionDB/2-3-dimetil-pentano"
            },
            correctIndex = 3,
            questionNumber = 12,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer12",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_011",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-metil-3-dimetil-pentano",
                "AnswerImages/IntroductionDB/3-metil-pentano",
                "AnswerImages/IntroductionDB/2-metil-butanol",
                "AnswerImages/IntroductionDB/2-3-dimetil-pentano"
            },
            correctIndex = 3,
            questionNumber = 13,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer13",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_013",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Compostos orgânicos insaturados podem ser classificados como isômeros cis e trans. Assinale a alternativa que representa um isômero cis.",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-4-hexadieno",
                "AnswerImages/IntroductionDB/2-hexeno",
                "AnswerImages/IntroductionDB/cis-3-hexeno",
                "AnswerImages/IntroductionDB/trans-3-hexeno"
            },
            correctIndex = 2,
            questionNumber = 14,   
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_014",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Assinale a alternativa que representa um isômero trans.",
            answers = new string[] {
                "AnswerImages/IntroductionDB/benzeno",
                "AnswerImages/IntroductionDB/trans-3-hexeno",
                "AnswerImages/IntroductionDB/cis-3-hexeno",
                "AnswerImages/IntroductionDB/anilina"
            },
            correctIndex = 1,
            questionNumber = 15,   
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_015",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Alcoóis são compostos orgânicos onde o grupo -OH está ligado a um carbono com hibridação sp3 (carbono saturado com 4 ligações simples). Qual estrutura representa um álcool?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-2-pentenol",
                "AnswerImages/IntroductionDB/fenol",
                "AnswerImages/IntroductionDB/2-butanol",
                "AnswerImages/IntroductionDB/metil-propil-eter"
                },
            correctIndex = 2,
            questionNumber = 15,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_015",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Álcoois são classificados pelo número de carbonos ligados ao carbono que carrega o -OH. Álcool primário: 1 carbono vizinho. Secundário: 2 carbonos vizinhos. Terciário: 3 carbonos vizinhos. Qual estrutura é um álcool secundário?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/fenol",
                "AnswerImages/IntroductionDB/2-butanol",
                "AnswerImages/IntroductionDB/butanol",
                "AnswerImages/IntroductionDB/2-metil-2-butanol"
                },
            correctIndex = 1,
            questionNumber = 16,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_016",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Assinale a estrutura que apresenta um álcool terciário.",
            answers = new string[] {
                "AnswerImages/IntroductionDB/fenol",
                "AnswerImages/IntroductionDB/2-butanol",
                "AnswerImages/IntroductionDB/butanol",
                "AnswerImages/IntroductionDB/2-metil-2-butanol"
                },
            correctIndex = 3,
            questionNumber = 17,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_017",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Cetonas são compostos orgânicos que contêm um grupo carbonila (C=O) ligado a dois carbonos diferentes, ou seja, a carbonila nunca está na extremidade da cadeia carbônica. Qual estrutura é uma cetona?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/propanal",
                "AnswerImages/IntroductionDB/2-butanona",
                "AnswerImages/IntroductionDB/propanoato-de-metila",
                "AnswerImages/IntroductionDB/acido-propanoico"
                },
            correctIndex = 1,
            questionNumber = 18,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_018",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Alguns açúcares, chamados cetoses, possuem um grupo carbonila (C=O) de uma cetona em sua estrutura. Em cetoses a carbonila está ligada a dois carbonos diferentes, nunca na ponta. Qual estrutura é uma cetose?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/propanoato-de-metila",
                "AnswerImages/IntroductionDB/propanal",
                "AnswerImages/IntroductionDB/aldose",
                "AnswerImages/IntroductionDB/cetose"
                },
            correctIndex = 3,
            questionNumber = 19,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_019",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Abaixo existem três compostos isômeros. Ou seja, mesma fórmula molécular e diferentes fórmulas estruturais. Assinale o composto que não é um isômero.",
            answers = new string[] {
                "AnswerImages/IntroductionDB/ciclo-hexanol",
                "AnswerImages/IntroductionDB/2-metil-2-butanol",
                "AnswerImages/IntroductionDB/2-2-hexenol",
                "AnswerImages/IntroductionDB/ciclo-heptano-eter"
            },
            correctIndex = 1,
            questionNumber = 20,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_020",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Aldeídos são compostos com grupo carbonila (C=O) ligado a um carbono e a um hidrogênio. A carbonila sempre fica na extremidade da cadeia carbônica. O carbono sp2 da carbonila tem apenas um vizinho carbônico. Qual estrutura é um aldeído?",
            answers = new string[] {
               "AnswerImages/IntroductionDB/propanal",
               "AnswerImages/IntroductionDB/2-butanona",
               "AnswerImages/IntroductionDB/propanoato-de-metila",
               "AnswerImages/IntroductionDB/acido-propanoico"
                },
            correctIndex = 0,
            questionNumber = 21,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_021",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Alguns açúcares, chamados aldose, possuem um grupo carbonila (C=O) de um aldeído em sua estrutura. Em aldoses a carbonila está presente na extremidade da cadeia carbônica. Qual estrutura é uma aldose?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/propanoato-de-metila",
                "AnswerImages/IntroductionDB/propanal",
                "AnswerImages/IntroductionDB/aldose",
                "AnswerImages/IntroductionDB/cetose"
                },
            correctIndex = 2,
            questionNumber = 22,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_022",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Os ácidos carboxílicos apresentam o grupo carboxila (-COOH), que combina carbonila (C=O) ligada a uma hidroxila (-OH). A carboxila sempre fica na extremidade da cadeia. Qual é um ácido carboxílico?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/propanamida",
                "AnswerImages/IntroductionDB/n-metil-propamida",
                "AnswerImages/IntroductionDB/propanoato-de-metila",
                "AnswerImages/IntroductionDB/acido-propanoico"
            },
            correctIndex = 3,
            questionNumber = 23,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_023",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Ácidos graxos são moléculas compostas por uma longa cadeia carbônica (geralmente 12-18 carbonos) com um grupo carboxila (-COOH) na extremidade. Quanto maior a cadeia, mais hidrofóbico é o ácido graxo. Assinale a estrutura do ácido graxo?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/acido-propanoico",
                "AnswerImages/IntroductionDB/acido-graxo",
                "AnswerImages/IntroductionDB/hidrocarboneto-saturado",
                "AnswerImages/IntroductionDB/hidrocarboneto-insaturado"
                },
            correctIndex = 1,
            questionNumber = 24,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_024",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Ésteres são compostos formados pela reação entre um ácido carboxílico e um álcool, com eliminação de água. Contêm o grupo funcional -COOR- (onde R é um hidrocarboneto). Qual estrutura é um éster?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/acido-propanoico",
                "AnswerImages/IntroductionDB/propanamida",
                "AnswerImages/IntroductionDB/propanoato-de-metila",
                "AnswerImages/IntroductionDB/butanol"
            },
            correctIndex = 2,
            questionNumber = 25,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_025",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/acido-propanoico",
                "AnswerImages/IntroductionDB/acetato-de-benzila",
                "AnswerImages/IntroductionDB/fenol",
                "AnswerImages/IntroductionDB/propanoato-de-metila"
            },
            correctIndex = 1,
            questionNumber = 26,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer26",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_026",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/n-dimetil-etanamina",
                "AnswerImages/IntroductionDB/propanamina",
                "AnswerImages/IntroductionDB/n-metil-propanamina",
                "AnswerImages/IntroductionDB/anilina"
            },
            correctIndex = 1,
            questionNumber = 27,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer27",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_027",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Assinale a amina secundária",
            answers = new string[] {
                "AnswerImages/IntroductionDB/n-dimetil-etanamina",
                "AnswerImages/IntroductionDB/propanamina",
                "AnswerImages/IntroductionDB/n-metil-propanamina",
                "AnswerImages/IntroductionDB/anilina"
            },
            correctIndex = 2,
            questionNumber = 28,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_028",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Assinale a amina terciária",
            answers = new string[] {
                "AnswerImages/IntroductionDB/n-dimetil-etanamina",
                "AnswerImages/IntroductionDB/propanamina",
                "AnswerImages/IntroductionDB/n-metil-propanamina",
                "AnswerImages/IntroductionDB/anilina"
            },
            correctIndex = 0,
            questionNumber = 29,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_029",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/n-dimetil-etanamina",
                "AnswerImages/IntroductionDB/propanamina",
                "AnswerImages/IntroductionDB/n-metil-propanamina",
                "AnswerImages/IntroductionDB/n-trimetil-etanamina"
            },
            correctIndex = 3,
            questionNumber = 30,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer30",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_030",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Dentre as aminas listadas, assinale a amina que possui um carbono quiral em sua cadeia carbônica.",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-metil-2-amino-butano",
                "AnswerImages/IntroductionDB/2-amino-butano",
                "AnswerImages/IntroductionDB/n-metil-propanamina",
                "AnswerImages/IntroductionDB/n-trimetil-etanamina"
            },
            correctIndex = 1,
            questionNumber = 31,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_031",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/aminoalcool",
                "AnswerImages/IntroductionDB/aminoacido",
                "AnswerImages/IntroductionDB/aminocetona",
                "AnswerImages/IntroductionDB/propanamida"
            },
            correctIndex = 1,
            questionNumber = 32,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer32",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_032",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-butanona",
                "AnswerImages/IntroductionDB/2-butanol",
                "AnswerImages/IntroductionDB/metil-propil-eter",
                "AnswerImages/IntroductionDB/metil-propil-tioeter"
            },
            correctIndex = 2,
            questionNumber = 33,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer33",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_033",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-butanona",
                "AnswerImages/IntroductionDB/2-butanol",
                "AnswerImages/IntroductionDB/metil-propil-eter",
                "AnswerImages/IntroductionDB/metil-propil-tioeter"
            },
            correctIndex = 3,
            questionNumber = 34,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer34",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_034",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/propanotiol",
                "AnswerImages/IntroductionDB/ciclo-hexatioeter",
                "AnswerImages/IntroductionDB/metil-propil-eter",
                "AnswerImages/IntroductionDB/metil-propil-tioeter"
            },
            correctIndex = 0,
            questionNumber = 35,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer35",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_035",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Amidas são compostos com grupo funcional -CO-N- (carbonila ligada a nitrogênio), e elas são a espinha dorçal para a formação de proteínas. Assinale a estrutura da amida?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/aminoacido",
                "AnswerImages/IntroductionDB/aminocetona",
                "AnswerImages/IntroductionDB/propanamida",
                "AnswerImages/IntroductionDB/anilina"
            },
            correctIndex = 2,
            questionNumber = 36,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_036",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Iminas são compostos com grupo funcional -C=N- (ligação dupla carbono-nitrogênio). Diferem de amidas e aminas, estão presentes em diversas moléculas biológicas. Assinale o composto que possui grupo funcional imina?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/propanamida",
                "AnswerImages/IntroductionDB/aminocetona",
                "AnswerImages/IntroductionDB/cetose",
                "AnswerImages/IntroductionDB/histidina"
            },
            correctIndex = 3,
            questionNumber = 37,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_037",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        // Questão 38
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual das seguintes moléculas é uma amina terciária?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/n-dimetil-etanamina",
                "AnswerImages/IntroductionDB/2-metil-2-amino-butano",
                "AnswerImages/IntroductionDB/2-amino-butano",
                "AnswerImages/IntroductionDB/n-trimetil-etanamina"
            },
            correctIndex = 0,
            questionNumber = 38,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_038",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "remember",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        // Questão 39
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-metil-butanal",
                "AnswerImages/IntroductionDB/3-metil-2-butanona",
                "AnswerImages/IntroductionDB/2-butanona",
                "AnswerImages/IntroductionDB/2-butanol"
            },
            correctIndex = 1,
            questionNumber = 39,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer39",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_039",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "apply",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        

        // Questão 40
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual estrutura representa um álcool terciário?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-butanol",
                "AnswerImages/IntroductionDB/ciclo-exanol",
                "AnswerImages/IntroductionDB/2-metil-2-butanol",
                "AnswerImages/IntroductionDB/fenol"
            },
            correctIndex = 2,
            questionNumber = 40,        
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_040",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "remember",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 41
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual das opções abaixo é um éter?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/n-metil-propanamina",
                "AnswerImages/IntroductionDB/pirano",
                "AnswerImages/IntroductionDB/2-2-pentenol",
                "AnswerImages/IntroductionDB/piridina"
            },
            correctIndex = 1,
            questionNumber = 41,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_041",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "remember",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 42
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual fórmula geral representa um álcool?",
            answers = new string[] {
                "R-CHO",
                "R-COOH",
                "R-OH",
                "R-O-R'"
            },
            correctIndex = 2,
            questionNumber = 42,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_042",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "remember",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 43
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Porque têm tamanhos diferentes",
                "Porque têm grupos funcionais diferentes e interagem de forma diferente",
                "Porque são feitos de elementos diferentes",
                "Não há nenhuma diferença real entre eles"
            },
            correctIndex = 1,
            questionNumber = 43,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer43",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_043",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "understand",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 44
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "O aldeído tem a dupla C=O no final da cadeia; cetona no meio",
                "O aldeído tem mais átomos de carbono",
                "O aldeído tem a dupla C=O no meio da cadeia; cetona no final",
                "Não há diferença significativa"
            },
            correctIndex = 0,
            questionNumber = 44,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer44",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_044",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "understand",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 45
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "porque o álcool faz interações intermoleculares mais fracas",
                "Porque o grupo -OH forma ligações de hidrogênio intermoleculares",
                "Porque o álcool é mais denso",
                "Porque tem mais prótons no núcleo"
            },
            correctIndex = 1,
            questionNumber = 45,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer45",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_045",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "understand",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 46
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual das seguintes afirmações é correta sobre isômeros?",
            answers = new string[] {
                "Isômeros têm a mesma fórmula molecular e sempre as mesmas propriedades",
                "Isômeros têm fórmulas moleculares diferentes",
                "Isômeros têm a mesma fórmula molecular mas estruturas diferentes",
                "Isômeros são tipos diferentes de moléculas não relacionadas"
            },
            correctIndex = 2,
            questionNumber = 46,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_046",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "understand",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 47
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "O que significa dizer que um carbono tem hibridação sp3?",
            answers = new string[] {
                "O carbono está ligado a apenas oxigênio",
                "O carbono faz uma dupla ligação",
                "O carbono faz 4 ligações simples em geometria tetraédrica",
                "O carbono faz 3 ligações duplas"
            },
            correctIndex = 2,
            questionNumber = 47,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "biochem_047",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "understand",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 48
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/IntroductionDB/propanol",
                "AnswerImages/IntroductionDB/metil-etil-eter",
                "AnswerImages/IntroductionDB/propanal",
                "AnswerImages/IntroductionDB/2-propanol"
            },
            correctIndex = 2,
            questionNumber = 48,
            isImageAnswer = true,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer48",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_048",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "apply",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 49
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual dos seguintes compostos não é um álcool?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/2-butanol",
                "AnswerImages/IntroductionDB/fenol",
                "AnswerImages/IntroductionDB/2-propanol",
                "AnswerImages/IntroductionDB/ciclo-hexanol"
            },
            correctIndex = 1,
            questionNumber = 49,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_049",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "apply",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 50
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual estrutura representa uma imina?",
            answers = new string[] {
                "AnswerImages/IntroductionDB/piridina",
                "AnswerImages/IntroductionDB/anilina",
                "AnswerImages/IntroductionDB/n-trimetil-etanamina",
                "AnswerImages/IntroductionDB/aminocetona"
            },
            correctIndex = 0,
            questionNumber = 50,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_050",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "apply",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 51
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Assinale a estrutura de um aminoácido que possui o grupo funcional tiol",
            answers = new string[] {
                "AnswerImages/IntroductionDB/aminoacido",
                "AnswerImages/IntroductionDB/cisteina",
                "AnswerImages/IntroductionDB/metionina",
                "AnswerImages/IntroductionDB/histidina"
            },
            correctIndex = 1,
            questionNumber = 51,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_051",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "apply",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 52
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Assinale a estrutura do aminoácido que possui o grupo funcional tioéter",
            answers = new string[] {
                "AnswerImages/IntroductionDB/aminoacido",
                "AnswerImages/IntroductionDB/cisteina",
                "AnswerImages/IntroductionDB/metionina",
                "AnswerImages/IntroductionDB/histidina"
            },
            correctIndex = 2,
            questionNumber = 52,
            isImageAnswer = true,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_052",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "apply",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 53
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "2,2-dimetil-propano, porque é o mais compacto",
                "Pentano linear, porque tem a maior área de superfície para interações",
                "2-metil-butano, porque está no meio",
                "Todos têm o mesmo ponto de ebulição"
            },
            correctIndex = 1,
            questionNumber = 53,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer53",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_053",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "analyze",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 54
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Ambos têm a mesma estrutura e propriedades",
                "Ambos têm a mesma fórmula molecular, mas posições diferentes do C=O",
                "O aldeído é sempre mais tóxico que a cetona",
                "A cetona tem uma dupla ligação, o aldeído não"
            },
            correctIndex = 1,
            questionNumber = 54,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer54",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_054",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "analyze",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 55
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Isomeria estrutural",
                "Isomeria espacial (geométrica)",
                "Isomeria óptica",
                "Isomeria funcional"
            },
            correctIndex = 1,
            questionNumber = 55,
            isImageAnswer = false,
            isImageQuestion = true,
            questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer55",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_055",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "analyze",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        // Questão 56
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Um aluno afirma: 'Todos os álcoois são mais solúveis em água que seus éteres correspondentes.' Avalie essa afirmação.",
            answers = new string[] {
                "Verdadeira, todos os álcoois formam prontes de hidrogênio com água",
                "Falsa, a solubilidade depende da cadeia carbônica, não do grupo funcional",
                "Verdadeira apenas para álcoois primários",
                "A afirmação está correta em geral, pois álcoois têm -OH"
            },
            correctIndex = 0,
            questionNumber = 56,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_056",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "evaluate",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 57
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual critério é MAIS IMPORTANTE para classificar uma estrutura como 'álcool primário' vs 'álcool secundário'?",
            answers = new string[] {
                "O tamanho total da molécula",
                "O número de carbonos ligados ao carbono que carrega o -OH",
                "A cor da solução",
                "Se a molécula tem uma dupla ligação"
            },
            correctIndex = 1,
            questionNumber = 57,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_057",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "evaluate",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },

        // Questão 58
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Um composto possui em sua fórmula molecular apenas C, H e O. Ele não faz ligações de hidrogênio intermoleculares. Qual seria a conclusão mais apropriada sobre sua estrutura?",
            answers = new string[] {
                "Provavelmente ser um ácido carboxílico",
                "Deve ser um álcool",
                "Provavelmente é um éster ou éter, não um álcool",
                "Deve conter uma dupla ligação C=C"
            },
            correctIndex = 2,
            questionNumber = 58,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "biochem_058",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "evaluate",
            conceptTags = null,
            prerequisites = null,
            // questionHint = null
        },

   };

    public List<Question> GetQuestions() => questions;
    public QuestionSet GetQuestionSetType() => QuestionSet.biochem;
    public string GetDatabankName()  => "BiochemistryIntroductionQuestionDatabase";
    public string GetDisplayName()   => "Introdução à Bioquímica";
    public bool IsDatabaseInDevelopment() => databaseInDevelopment;
}