using System.Collections.Generic;
using QuestionSystem;

public class BiochemistryIntroductionQuestionDatabase : IQuestionDatabase
{
    private bool databaseInDevelopment = false;

    private List<Question> questions = new List<Question>
    {
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "São características de sistemas vivos, exceto:",
        //     answers = new string[] {
        //         "Utilizar a energia do ambiente",
        //         "Possuir organização microcópica.",
        //         "Capacidade de se autoreplicar",
        //         "Não respondem as alterações do ambiente"
        //     },
        //     correctIndex = 3,
        //     questionNumber = 1,
        //     isImageAnswer = false,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_001",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Qual a teoria que afirmava que os seres vivos possuíam uma força vital?",
        //     answers = new string[] {
        //         "Teoria da abiogênese",
        //         "Teoria da biogênese",
        //         "Vitalismo",
        //         "Teoria celular"
        //     },
        //     correctIndex = 2,
        //     questionNumber = 2,
        //     isImageAnswer = false,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_002",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Qual fato mais contribuiu para a perda de credibilidade da doutrina do vitalismo?",
        //     answers = new string[] {
        //         "A criação da tabela periódica dos elementos",
        //         "O fim da crença na geração espontânea dos seres vivos",
        //         "O desenvolvimento da teoria atómica dos elementos",
        //         "A lei da conservação das massas"
        //     },
        //     correctIndex = 1,
        //     questionNumber = 3,
        //     isImageAnswer = false,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_003",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Qual a importância de Louis Pasteur para o desenvolvimento da Bioquímica?",
        //     answers = new string[] {
        //         "Pasteur contribuiu para demonstrar que a vida surgia espontaneamente.",
        //         "Pasteur estabeleceu a relação entre microorganismos e doenças, desafiando a geração espontânea.",
        //         "Pasteur desenvolveu métodos de esterilização de alimentos por luz ultravioleta.",
        //         "Pasteur foi o primeiro a descobrir o DNA como material genético."
        //     },
        //     correctIndex = 1,
        //     questionNumber = 4,
        //     isImageAnswer = false,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_004",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Quais os quatro elementos mais abundantes nos organismos vivos?",
        //     answers = new string[] { 
        //         "H, O, N, C", 
        //         "C, H, O, P", 
        //         "C, N, O, S", 
        //         "H, O, P, S" 
        //         },
        //     correctIndex = 0,
        //     questionNumber = 5,
        //     isImageAnswer = false,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_005",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Os seres vivos são caracterizados por um alto grau de complexidade química e organização molecular. Qual apção melhor se alinha com essa afirmação?",
            // answers = new string[] {
                // "Os seres vivos são formados por moléculas simples, sem organização interna definida",
                // "Os seres vivos apresentam moléculas complexas, como proteínas e lipídios",
                // "Os seres vivos não dependem de reações químicas para manter suas funções vitais",
                // "Os seres vivos possuem apenas substâncias inorgânicas em sua composição química"
            // },
            // correctIndex = 1,
            // questionNumber = 6,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_006",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Qual é a importância dos grupos funcionais nas moléculas orgânicas que formam macromoléculas?",
            // answers = new string[] {
                // "Definem propriedades e reações das moléculas",
                // "Tornam todas as moléculas iguais.",
                // "Existem apenas em moléculas inorgânicas.",
                // "Impedem a formação de macromoléculas."
            // },
            // correctIndex = 0,
            // questionNumber = 7,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_007",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Identifique a estrutura que representa um hidrocarboneto ramificado",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/benzeno",
        //         "AnswerImages/IntroductionDB/2-butanol",
        //         "AnswerImages/IntroductionDB/2-3-dimetil-pentano",
        //         "AnswerImages/IntroductionDB/propanamina"
        //     },
        //     correctIndex = 2,
        //     questionNumber = 8,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_008",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Identifique a estrutura molecular do ácido carboxílico",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/2-butanona",
        //         "AnswerImages/IntroductionDB/metanoato-de-propila",
        //         "AnswerImages/IntroductionDB/propanal",
        //         "AnswerImages/IntroductionDB/acido-propanoico"
        //     },
        //     correctIndex = 3,
        //     questionNumber = 9,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_009",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Identifique a estrutura molecular da amina",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/n-trimetil-etanamina",
        //         "AnswerImages/IntroductionDB/propanamida",
        //         "AnswerImages/IntroductionDB/trans-3-hexeno",
        //         "AnswerImages/IntroductionDB/fenol"
        //     },
        //     correctIndex = 0,
        //     questionNumber = 10,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_010",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/haxano",
        //         "AnswerImages/IntroductionDB/ciclo-hexano",
        //         "AnswerImages/IntroductionDB/benzeno",
        //         "AnswerImages/IntroductionDB/3-metil-haxano"
        //     },
        //     correctIndex = 1,
        //     questionNumber = 11,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer11",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_011",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/2-metil-3-dimetil-pentano",
        //         "AnswerImages/IntroductionDB/ciclo-hexano",
        //         "AnswerImages/IntroductionDB/benzeno",
        //         "AnswerImages/IntroductionDB/2-3-dimetil-pentano"
        //     },
        //     correctIndex = 3,
        //     questionNumber = 12,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer12",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_011",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/2-metil-3-dimetil-pentano",
        //         "AnswerImages/IntroductionDB/3-metil-pentano",
        //         "AnswerImages/IntroductionDB/2-metil-butanol",
        //         "AnswerImages/IntroductionDB/2-3-dimetil-pentano"
        //     },
        //     correctIndex = 3,
        //     questionNumber = 13,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer13",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_013",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Compostos orgânicos insaturados podem ser classificados como isômeros cis e trans. Assinale a alternativa que representa um isômero cis.",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/2-4-hexadieno",
        //         "AnswerImages/IntroductionDB/2-hexeno",
        //         "AnswerImages/IntroductionDB/cis-3-hexeno",
        //         "AnswerImages/IntroductionDB/trans-3-hexeno"
        //     },
        //     correctIndex = 2,
        //     questionNumber = 14,   
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_014",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Assinale a alternativa que representa um isômero trans.",
            // answers = new string[] {
                // "AnswerImages/IntroductionDB/benzeno",
                // "AnswerImages/IntroductionDB/trans-3-hexeno",
                // "AnswerImages/IntroductionDB/cis-3-hexeno",
                // "AnswerImages/IntroductionDB/anilina"
            // },
            // correctIndex = 1,
            // questionNumber = 15,   
            // isImageAnswer = true,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_015",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Alcoóis são compostos orgânicos onde o grupo -OH está ligado a um carbono com hibridação sp3 (carbono saturado com 4 ligações simples). Qual estrutura representa um álcool?",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/2-2-pentenol",
        //         "AnswerImages/IntroductionDB/fenol",
        //         "AnswerImages/IntroductionDB/2-butanol",
        //         "AnswerImages/IntroductionDB/metil-propil-eter"
        //         },
        //     correctIndex = 2,
        //     questionNumber = 15,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_015",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Álcoois são classificados pelo número de carbonos ligados ao carbono que carrega o -OH. Álcool primário: 1 carbono vizinho. Secundário: 2 carbonos vizinhos. Terciário: 3 carbonos vizinhos. Qual estrutura é um álcool secundário?",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/fenol",
        //         "AnswerImages/IntroductionDB/2-butanol",
        //         "AnswerImages/IntroductionDB/butanol",
        //         "AnswerImages/IntroductionDB/2-metil-2-butanol"
        //         },
        //     correctIndex = 1,
        //     questionNumber = 16,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_016",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Assinale a estrutura que apresenta um álcool terciário.",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/fenol",
        //         "AnswerImages/IntroductionDB/2-butanol",
        //         "AnswerImages/IntroductionDB/butanol",
        //         "AnswerImages/IntroductionDB/2-metil-2-butanol"
        //         },
        //     correctIndex = 3,
        //     questionNumber = 17,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_017",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Cetonas são compostos orgânicos que contêm um grupo carbonila (C=O) ligado a dois carbonos diferentes, ou seja, a carbonila nunca está na extremidade da cadeia carbônica. Qual estrutura é uma cetona?",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/propanal",
        //         "AnswerImages/IntroductionDB/2-butanona",
        //         "AnswerImages/IntroductionDB/propanoato-de-metila",
        //         "AnswerImages/IntroductionDB/acido-propanoico"
        //         },
        //     correctIndex = 1,
        //     questionNumber = 18,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_018",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Alguns açúcares, chamados cetoses, possuem um grupo carbonila (C=O) de uma cetona em sua estrutura. Em cetoses a carbonila está ligada a dois carbonos diferentes, nunca na ponta. Qual estrutura é uma cetose?",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/propanoato-de-metila",
        //         "AnswerImages/IntroductionDB/propanal",
        //         "AnswerImages/IntroductionDB/aldose",
        //         "AnswerImages/IntroductionDB/cetose"
        //         },
        //     correctIndex = 3,
        //     questionNumber = 19,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_019",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Abaixo existem três compostos isômeros. Ou seja, mesma fórmula molécular e diferentes fórmulas estruturais. Assinale o composto que não é um isômero.",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/ciclo-hexanol",
        //         "AnswerImages/IntroductionDB/2-metil-2-butanol",
        //         "AnswerImages/IntroductionDB/2-2-hexenol",
        //         "AnswerImages/IntroductionDB/ciclo-heptano-eter"
        //     },
        //     correctIndex = 1,
        //     questionNumber = 20,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_020",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Aldeídos são compostos com grupo carbonila (C=O) ligado a um carbono e a um hidrogênio. A carbonila sempre fica na extremidade da cadeia carbônica. O carbono sp2 da carbonila tem apenas um vizinho carbônico. Qual estrutura é um aldeído?",
        //     answers = new string[] {
        //        "AnswerImages/IntroductionDB/propanal",
        //        "AnswerImages/IntroductionDB/2-butanona",
        //        "AnswerImages/IntroductionDB/propanoato-de-metila",
        //        "AnswerImages/IntroductionDB/acido-propanoico"
        //         },
        //     correctIndex = 0,
        //     questionNumber = 21,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_021",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Alguns açúcares, chamados aldose, possuem um grupo carbonila (C=O) de um aldeído em sua estrutura. Em aldoses a carbonila está presente na extremidade da cadeia carbônica. Qual estrutura é uma aldose?",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/propanoato-de-metila",
        //         "AnswerImages/IntroductionDB/propanal",
        //         "AnswerImages/IntroductionDB/aldose",
        //         "AnswerImages/IntroductionDB/cetose"
        //         },
        //     correctIndex = 2,
        //     questionNumber = 22,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_022",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Os ácidos carboxílicos apresentam o grupo carboxila (-COOH), que combina carbonila (C=O) ligada a uma hidroxila (-OH). A carboxila sempre fica na extremidade da cadeia. Qual é um ácido carboxílico?",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/propanamida",
        //         "AnswerImages/IntroductionDB/n-metil-propamida",
        //         "AnswerImages/IntroductionDB/propanoato-de-metila",
        //         "AnswerImages/IntroductionDB/acido-propanoico"
        //     },
        //     correctIndex = 3,
        //     questionNumber = 23,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_023",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Ácidos graxos são moléculas compostas por uma longa cadeia carbônica (geralmente 12-18 carbonos) com um grupo carboxila (-COOH) na extremidade. Quanto maior a cadeia, mais hidrofóbico é o ácido graxo. Assinale a estrutura do ácido graxo?",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/acido-propanoico",
        //         "AnswerImages/IntroductionDB/acido-graxo",
        //         "AnswerImages/IntroductionDB/hidrocarboneto-saturado",
        //         "AnswerImages/IntroductionDB/hidrocarboneto-insaturado"
        //         },
        //     correctIndex = 1,
        //     questionNumber = 24,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_024",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question
        // {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Ésteres são compostos formados pela reação entre um ácido carboxílico e um álcool, com eliminação de água. Contêm o grupo funcional -COOR- (onde R é um hidrocarboneto). Qual estrutura é um éster?",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/acido-propanoico",
        //         "AnswerImages/IntroductionDB/propanamida",
        //         "AnswerImages/IntroductionDB/propanoato-de-metila",
        //         "AnswerImages/IntroductionDB/butanol"
        //     },
        //     correctIndex = 2,
        //     questionNumber = 25,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_025",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     // questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/acido-propanoico",
        //         "AnswerImages/IntroductionDB/acetato-de-benzila",
        //         "AnswerImages/IntroductionDB/fenol",
        //         "AnswerImages/IntroductionDB/propanoato-de-metila"
        //     },
        //     correctIndex = 1,
        //     questionNumber = 26,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer26",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_026",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/n-dimetil-etanamina",
        //         "AnswerImages/IntroductionDB/propanamina",
        //         "AnswerImages/IntroductionDB/n-metil-propanamina",
        //         "AnswerImages/IntroductionDB/anilina"
        //     },
        //     correctIndex = 1,
        //     questionNumber = 27,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer27",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_027",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Assinale a amina secundária",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/n-dimetil-etanamina",
        //         "AnswerImages/IntroductionDB/propanamina",
        //         "AnswerImages/IntroductionDB/n-metil-propanamina",
        //         "AnswerImages/IntroductionDB/anilina"
        //     },
        //     correctIndex = 2,
        //     questionNumber = 28,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_028",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Assinale a amina terciária",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/n-dimetil-etanamina",
        //         "AnswerImages/IntroductionDB/propanamina",
        //         "AnswerImages/IntroductionDB/n-metil-propanamina",
        //         "AnswerImages/IntroductionDB/anilina"
        //     },
        //     correctIndex = 0,
        //     questionNumber = 29,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_029",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/n-dimetil-etanamina",
        //         "AnswerImages/IntroductionDB/propanamina",
        //         "AnswerImages/IntroductionDB/n-metil-propanamina",
        //         "AnswerImages/IntroductionDB/n-trimetil-etanamina"
        //     },
        //     correctIndex = 3,
        //     questionNumber = 30,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer30",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_030",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "Dentre as aminas listadas, assinale a amina que possui um carbono quiral em sua cadeia carbônica.",
            // answers = new string[] {
            //     "AnswerImages/IntroductionDB/2-metil-2-amino-butano",
            //     "AnswerImages/IntroductionDB/2-amino-butano",
            //     "AnswerImages/IntroductionDB/n-metil-propanamina",
            //     "AnswerImages/IntroductionDB/n-trimetil-etanamina"
            // },
        //     correctIndex = 1,
        //     questionNumber = 31,
        //     isImageAnswer = true,
        //     isImageQuestion = false,
        //     questionImagePath = "",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_031",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/aminoalcool",
        //         "AnswerImages/IntroductionDB/aminoacido",
        //         "AnswerImages/IntroductionDB/aminocetona",
        //         "AnswerImages/IntroductionDB/propanamida"
        //     },
        //     correctIndex = 1,
        //     questionNumber = 32,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer32",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_032",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/2-butanona",
        //         "AnswerImages/IntroductionDB/2-butanol",
        //         "AnswerImages/IntroductionDB/metil-propil-eter",
        //         "AnswerImages/IntroductionDB/metil-propil-tioeter"
        //     },
        //     correctIndex = 2,
        //     questionNumber = 33,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer33",
        //     questionLevel = 2,
        //     questionInDevelopment = false,
        //     globalId = "biochem_033",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/2-butanona",
        //         "AnswerImages/IntroductionDB/2-butanol",
        //         "AnswerImages/IntroductionDB/metil-propil-eter",
        //         "AnswerImages/IntroductionDB/metil-propil-tioeter"
        //     },
        //     correctIndex = 3,
        //     questionNumber = 34,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer34",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_034",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        // new Question {
        //     questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
        //     questionText = "",
        //     answers = new string[] {
        //         "AnswerImages/IntroductionDB/propanotiol",
        //         "AnswerImages/IntroductionDB/ciclo-hexatioeter",
        //         "AnswerImages/IntroductionDB/metil-propil-eter",
        //         "AnswerImages/IntroductionDB/metil-propil-tioeter"
        //     },
        //     correctIndex = 0,
        //     questionNumber = 35,
        //     isImageAnswer = true,
        //     isImageQuestion = true,
        //     questionImagePath = "QuestionImages/IntroductionDB/introductionDB_ImageQuestionContainer35",
        //     questionLevel = 1,
        //     questionInDevelopment = false,
        //     globalId = "biochem_035",
        //     topic = "biochem",
        //     subtopic = null,
        //     displayName = "Introdução à Bioquímica",
        //     bloomLevel = "unclassified",
        //     conceptTags = null,
        //     prerequisites = null,
        //     questionHint = null
        // },
        new Question {
            questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            questionText = "Qual a principal função do ATP na célula?",
            answers = new string[] {
                "Armazenamento de informação genética",
                "Transporte de moléculas",
                "Carreador de energia",
                "Catálise de reações"
                },
            correctIndex = 2,
            questionNumber = 36,
            isImageAnswer = false,
            isImageQuestion = false,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "biochem_036",
            topic = "biochem",
            subtopic = null,
            displayName = "Introdução à Bioquímica",
            bloomLevel = "unclassified",
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Qual a atividade que mais consome energia nas células?",
            // answers = new string[] {
                // "Transporte de íons",
                // "Síntese de macromoléculas",
                // "Respiração celular",
                // "Fotossíntese"
                // },
            // correctIndex = 1,
            // questionNumber = 37,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_037",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "O que são complexos supramoleculares?",
            // answers = new string[] {
                // "Moléculas pequenas.",
                // "Macromoléculas.",
                // "Agregados de macromoléculas.",
                // "Componentes celulares."
            // },
            // correctIndex = 2,
            // questionNumber = 38,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_038",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "O que é o citoesqueleto?",
            // answers = new string[] {
                // "Rede de proteínas que dá forma e rigidez às células.",
                // "Rede de carboidratos que dá forma e rigidez às células.",
                // "Rede de lipídeos que dá forma e rigidez às células.",
                // "Rede de ácidos nucléicos que dá forma e rigidez às células."
            // },
            // correctIndex = 0,
            // questionNumber = 39,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_039",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "O que a entropia mede?",
            // answers = new string[] {
                // "Energia",
                // "Trabalho",
                // "Desordem",
                // "Ordem"
                // },
            // correctIndex = 2,
            // questionNumber = 40,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_040",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Em qual estado os organismos vivos existem em relação ao seu meio?",
            // answers = new string[] {
                // "Equilíbrio",
                // "Estado estacionário dinâmico",
                // "Alta entropia",
                // "Baixa entropia"
                // },
            // correctIndex = 1,
            // questionNumber = 41,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_041",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Em que tipo de ambiente a vida provavelmente surgiu?",
            // answers = new string[] {
                // "Ambiente quente",
                // "Ambiente frio",
                // "Ambiente seco",
                // "Ambiente oceânico"
                // },
            // correctIndex = 3,
            // questionNumber = 42,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_042",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Quais os três estágios geralmente aceitos para o desenvolvimento da vida?",
            // answers = new string[] {
                // "Evolução química, auto-organização, evolução biológica",
                // "Evolução química, replicação, mutação",
                // "Auto-organização, replicação, seleção natural",
                // "Evolução biológica, seleção natural, extinção"
            // },
            // correctIndex = 0,
            // questionNumber = 43,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_043",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Qual a característica principal que torna o carbono único na formação de biomoléculas?",
            // answers = new string[] {
                // "Forma apenas ligações simples.",
                // "Forma ligações simples, duplas e triplas.",
                // "É o elemento mais abundante na Terra.",
                // "É altamente reativo."
            // },
            // correctIndex = 1,
            // questionNumber = 44,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_044",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Qual experimento simulou a síntese de compostos orgânicos na Terra primitiva?",
            // answers = new string[] {
                // "Experimento de Miller-Urey",
                // "Experimento de Hershey-Chase",
                // "Experimento de Meselson-Stahl",
                // "Experimento de Griffith"
                // },
            // correctIndex = 0,
            // questionNumber = 45,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_045",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Qual o tipo de atmosfera que provavelmente existia na Terra primitiva?",
            // answers = new string[] {
                // "Atmosfera oxidante",
                // "Atmosfera redutora",
                // "Atmosfera neutra",
                // "Atmosfera rica em oxigênio"
                // },
            // correctIndex = 1,
            // questionNumber = 46,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_046",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "O que impulsionou o desenvolvimento de rotas metabólicas nas células?",
            // answers = new string[] {
                // "Aumento da temperatura.",
                // "Diminuição da temperatura.",
                // "Competição por recursos.",
                // "Mutações genéticas."
            // },
            // correctIndex = 2,
            // questionNumber = 47,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_047",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Que processo metabólico representou uma solução para a crise de energia enfrentada pelos primeiros organismos vivos?",
            // answers = new string[] {
                // "Respiração aeróbica",
                // "Fermentação",
                // "Fotossíntes",
                // "Quimiossíntese"
            // },
            // correctIndex = 2,
            // questionNumber = 48,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_048",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        //  new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Selecione o aminoácido que não possui carbono quiral",
            // answers = new string[] {
                // "AnswerImages/AminoacidsDB/cisteina",
                // "AnswerImages/AminoacidsDB/glicina",
                // "AnswerImages/AminoacidsDB/alanina",
                // "AnswerImages/AminoacidsDB/histidina"
                // },
            // correctIndex = 1,
            // questionNumber = 49,
            // isImageAnswer = true,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_049",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Identifique o isômero cis nas estruturas abaixo",
            // answers = new string[] {
                // "AnswerImages/IntroductionDB/trans-dihidroxi-eteno",
                // "AnswerImages/IntroductionDB/cis-dihidroxi-eteno",
                // "AnswerImages/IntroductionDB/dihidroxi-eteno",
                // "AnswerImages/IntroductionDB/dihidroxi-eteno2"
            // },
            // correctIndex = 1,
            // questionNumber = 50,
            // isImageAnswer = true,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 2,
            // questionInDevelopment = false,
            // globalId = "biochem_050",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Qual das opções abaixo NÃO é considerada uma biomolécula fundamental?",
            // answers = new string[] {
                // "Proteína",
                // "Lipídio",
                // "Carboidrato",
                // "Água"
            // },
            // correctIndex = 3,
            // questionNumber = 51,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_051",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "O que diferencia os aminoácidos entre si, apesar de todos possuírem o mesmo grupo amino e carboxila?",
            // answers = new string[] {
                // "O número de átomos de hidrogênio",
                // "A cadeia lateral (grupo R)",
                // "O tipo de ligação peptídica",
                // "A presença de oxigênio no grupo carboxila"
            // },
            // correctIndex = 1,
            // questionNumber = 52,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_052",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "A bioquímica é o ramo da ciência que estuda:",
            // answers = new string[] {
                // "As leis da física aplicadas ao corpo humano.",
                // "A estrutura dos organismos vivos no nível populacional.",
                // "As transformações químicas que ocorrem nos seres vivos.",
                // "As reações químicas em ambientes inorgânicos."
            // },
            // correctIndex = 2,
            // questionNumber = 53,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_053",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Qual é o principal solvente dos sistemas biológicos?",
            // answers = new string[] {
                // "Etanol",
                // "Água",
                // "Metano",
                // "Glicerol"
            // },
            // correctIndex = 1,
            // questionNumber = 54,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_054",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "As macromoléculas biológicas incluem:",
            // answers = new string[] {
                // "Proteínas, lipídios, carboidratos e ácidos nucleicos",
                // "Vitaminas, sais minerais e proteínas",
                // "Gases, água, lipídios e enzimas",
                // "Açúcares simples, ATP e DNA"
            // },
            // correctIndex = 0,
            // questionNumber = 55,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_055",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "A molécula de DNA é responsável principalmente por:",
            // answers = new string[] {
                // "Produzir energia imediata",
                // "Transportar oxigênio",
                // "Armazenar e transmitir informações genéticas",
                // "Formar membranas celulares"
            // },
            // correctIndex = 2,
            // questionNumber = 56,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_056",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Por que o a ATP é considerado a moeda energética da célula?",
            // answers = new string[] {
                // "É um lipídio armazenado em grandes quantidades",
                // "Armazena energia em suas ligações fosfato",
                // "É uma proteína que atua como enzima",
                // "Faz parte da estrutura dos ácidos nucleicos"
            // },
            // correctIndex = 1,
            // questionNumber = 57,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_057",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Qual é o principal carboidrato utilizado como fonte imediata de energia pelas células?",
            // answers = new string[] {
                // "Amido",
                // "Glicogênio",
                // "Glicose",
                // "Frutose"
            // },
            // correctIndex = 2,
            // questionNumber = 58,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_058",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "As enzimas são:",
            // answers = new string[] {
                // "Vitaminas essenciais à vida",
                // "Moléculas de DNA que controlam a divisão celular",
                // "Catalisadores biológicos, geralmente proteínas",
                // "Lipídios que fornecem energia"
            // },
            // correctIndex = 2,
            // questionNumber = 59,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_059",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Em organismos vivos, os lipídios têm como função principal:",
            // answers = new string[] {
                // "Formar cadeias polipeptídicas",
                // "Servir como catalisadores",
                // "Armazenar energia e compor membranas celulares",
                // "Atuar como código genético"
            // },
            // correctIndex = 2,
            // questionNumber = 60,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_060",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "A bioquímica surgiu como disciplina independente principalmente com:",
            // answers = new string[] {
                // "A descoberta da penicilina",
                // "O isolamento da ureia por Wöhler",
                // "A teoria celular de Schleiden e Schwann",
                // "A descoberta da dupla hélice do DNA"
            // },
            // correctIndex = 1,
            // questionNumber = 61,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_061",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Um dos principais objetivos da Bioquímica é:",
            // answers = new string[] {
                // "Entender as interações entre espécies diferentes",
                // "Explicar como as reações químicas sustentam os processos vitais",
                // "Descrever a anatomia dos organismos",
                // "Estudar apenas as doenças humanas"
            // },
            // correctIndex = 1,
            // questionNumber = 62,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_062",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // },    
        // new Question {
            // questionDatabankName = "BiochemistryIntroductionQuestionDatabase",
            // questionText = "Os principais elementos químicos que constituem os seres vivos são:",
            // answers = new string[] {
                // "C, H, O, N",
                // "Fe, Cu, Zn, Mg",
                // "Na, K, Cl, Ca",
                // "S, P, Cl, Ar"
            // },
            // correctIndex = 0,
            // questionNumber = 63,
            // isImageAnswer = false,
            // isImageQuestion = false,
            // questionImagePath = "",
            // questionLevel = 1,
            // questionInDevelopment = false,
            // globalId = "biochem_063",
            // topic = "biochem",
            // subtopic = null,
            // displayName = "Introdução à Bioquímica",
            // bloomLevel = "unclassified",
            // conceptTags = null,
            // prerequisites = null,
            // questionHint = null
        // }   
    };

    public List<Question> GetQuestions() => questions;
    public QuestionSet GetQuestionSetType() => QuestionSet.biochem;
    public string GetDatabankName()  => "BiochemistryIntroductionQuestionDatabase";
    public string GetDisplayName()   => "Introdução à Bioquímica";
    public bool IsDatabaseInDevelopment() => databaseInDevelopment;
}