using System.Collections.Generic;
using QuestionSystem;

public class NucleicAcidsQuestionDatabase : IQuestionDatabase
{
    private bool databaseInDevelopment = false;
    
    private List<Question> questions = new List<Question>
    {
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Quem primeiro isolou o ácido nucléico?",
            answers = new string[] { "Watson", "Crick", "Friedrich Miescher", "Chargaff" },
            correctIndex = 2,
            questionNumber = 1,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_001",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O cientista suíço Friedrich Miescher foi o primeiro pesquisador a isolar o ácido nucléico, em 1868. Durante seus estudos com células presentes em pus coletado de bandagens cirúrgicas, ele identificou uma substância rica em fósforo localizada no núcleo celular, que chamou de “nucleína”. Posteriormente, essa substância passou a ser conhecida como ácido nucleico, componente fundamental do DNA e do RNA." }
        },
        new Question
        {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a principal função do RNA na célula?",
            answers = new string[] { 
                "Armazenamento de informação genética", 
                "Síntese de proteínas", 
                "Catálise de reações", 
                "Transporte de íons" 
            },
            correctIndex = 1,
            questionNumber = 2,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_002",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA (ácido ribonucleico) tem como principal função participar do processo de síntese de proteínas nas células. Ele atua como intermediário entre a informação genética armazenada no DNA e a produção das proteínas necessárias para o funcionamento celular. Embora alguns vírus utilizem RNA como material genético, nas células o armazenamento principal ocorre no DNA." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Quais são os três componentes de um nucleotídeo?",
            answers = new string[] { 
                "Açúcar, base, fosfato", 
                "Açúcar, base, aminoácido", 
                "Base, aminoácido, fosfato", 
                "Açúcar, lipídeo, base" 
            },
            correctIndex = 0,
            questionNumber = 3,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_003",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os nucleotídeos são as unidades básicas que formam os ácidos nucleicos, como o DNA e o RNA. Cada nucleotídeo é composto por três partes fundamentais: um açúcar de cinco carbonos (pentose); uma base nitrogenada; e um ou mais fosfatos." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual açúcar está presente no RNA?",
            answers = new string[] { "Desoxirribose", "Ribose", "Glicose", "Frutose" },
            correctIndex = 1,
            questionNumber = 4,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_004",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA (ácido ribonucleico) possui como açúcar a ribose, uma pentose (açúcar com cinco carbonos). Esse componente faz parte da estrutura dos nucleotídeos que formam o RNA. A ribose diferencia o RNA do DNA, que possui outro açúcar chamado desoxirribose." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual açúcar está presente no DNA?",
            answers = new string[] { "Desoxirribose", "Ribose", "Glicose", "Frutose" },
            correctIndex = 0,
            questionNumber = 5,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_005",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O DNA (ácido desoxirribonucleico) possui como açúcar a desoxirribose, uma pentose (açúcar com cinco carbonos). Esse açúcar é fundamental para formar a cadeia estrutural do DNA junto ao grupo fosfato. A pentose diferencia o DNA do RNA. Enquanto o RNA possui ribose, a desoxirribose do DNA apresenta um átomo de oxigênio a menos em sua estrutura química, especificamente no carbono 2’. Essa diferença torna o DNA mais estável e menos suscetível à degradação química, característica importante para o armazenamento seguro da informação genética." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que são nucleosídeos?",
            answers = new string[] {
                "Açúcar + base",
                "Açúcar + base + fosfato",
                "Base + fosfato",
                "Açúcar + aminoácido"
            },
            correctIndex = 0,
            questionNumber = 6,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_006",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os nucleosídeos são moléculas formadas pela união de um açúcar pentose (ribose ou desoxirribose) com uma base nitrogenada. Eles representam uma parte da estrutura dos nucleotídeos, porém sem o grupo fosfato. Nucleosídeo = Açúcar (pentose) + Base Nitrogenada." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Identifique a estrutura do nucleosídeo",
            answers = new string[] {
                "AnswerImages/NucleicAcidDB/nucleotideo_di_fosfato",
                "AnswerImages/NucleicAcidDB/nucleotideo_mono_fosfato",
                "AnswerImages/NucleicAcidDB/nucleosideo",
                "AnswerImages/NucleicAcidDB/nucleotideo_tri_fosfato"
            },
            correctIndex = 2,
            questionNumber = 7,
            answerType = AnswerType.Image,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_007",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os nucleosídeos são moléculas formadas pela união de um açúcar pentose com uma base nitrogenada. Ou seja, diferente dos nucleotídeos, eles não apresentam grupo fosfato (PO4 3-)." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Quais bases são encontradas no RNA, mas não no DNA?",
            answers = new string[] { "Adenina, guanina", "Citosina, timina", "Uracila", "Timina, uracila" },
            correctIndex = 2,
            questionNumber = 8,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_008",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Tanto o RNA quanto o DNA apresentam as bases adenina (A), citosina (C) e guanina (G). Porém, não é comum encontrar a uracila (U) no DNA e não é comum encontrar a timina (T) no RNA. Portanto, dizemos que têm-se no DNA as bases A, T, C, G e no RNA as bases A, U, C, G." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Quais bases são encontradas no DNA, mas não no RNA?",
            answers = new string[] { "Adenina, guanina", "Citosina, timina", "Uracila", "Timina" },
            correctIndex = 3,
            questionNumber = 9,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_009",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Tanto o RNA quanto o DNA apresentam as bases adenina (A), citosina (C) e guanina (G). Porém, não é comum encontrar a uracila (U) no DNA e não é comum encontrar a timina (T) no RNA. Portanto, dizemos que têm-se no DNA as bases A, T, C, G e no RNA as bases A, U, C, G." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a função principal dos grupamentos fosfato nos nucleotídeos?",
            answers = new string[] { "Dar caráter básico", "Dar caráter ácido", "Formar ligações peptídicas", "Armazenar energia" },
            correctIndex = 1,
            questionNumber = 10,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_010",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os grupamentos fosfato presentes nos nucleotídeos têm como uma de suas principais características conferir caráter ácido às moléculas de DNA e RNA. Isso ocorre porque os grupos fosfato possuem carga negativa em condições fisiológicas, contribuindo para o comportamento ácido dos ácidos nucleicos e influenciando suas interações com proteínas e outras moléculas celulares." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Que tipo de ligação une os nucleotídeos em uma cadeia?",
            answers = new string[] { "Ligação peptídica", "Ligação glicosídica", "Ligação éster", "Ligação fosfodiéster" },
            correctIndex = 3,
            questionNumber = 11,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_011",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os nucleotídeos são unidos entre si nas cadeias de DNA e RNA por meio de ligações fosfodiéster, que ocorrem entre o grupo fosfato de um nucleotídeo e o grupo hidroxila do açúcar (pentose) de outro nucleotídeo." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a orientação das cadeias de DNA em uma dupla hélice?",
            answers = new string[] { "Paralela", "Antiparalela", "Perpendicular", "Aleatória" },
            correctIndex = 1,
            questionNumber = 12,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_012",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Na estrutura da dupla hélice do DNA, as duas cadeias polinucleotídicas estão orientadas em direções opostas. Isso significa que uma fita segue no sentido 5' → 3', enquanto a outra corre no sentido 3' → 5'. Essa disposição é chamada de antiparalela e é essencial para o emparelhamento das bases nitrogenadas (A-T e G-C), pois garante que as ligações de hidrogênio se formem de maneira estável e complementar." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que são pares de bases de Watson-Crick?",
            answers = new string[] {
                "A-T e G-C",
                "A-G e T-C",
                "A-C e G-T",
                "Qualquer combinação de bases."
            },
            correctIndex = 0,
            questionNumber = 13,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_013",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os pares de bases de Watson-Crick são as combinações específicas de nucleotídeos que se unem na molécula de DNA por meio de ligações de hidrogênio. Adenina (A) sempre se liga à Timina (T) através de duas ligações de hidrogênio, enquanto Guanina (G) se liga à Citosina (C) por três ligações de hidrogênio. Essa complementaridade é fundamental para a estabilidade da dupla hélice e para a fidelidade nos processos de replicação do DNA e transcrição." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual tipo de ligação mantém os pares de bases unidos no DNA?",
            answers = new string[] { "Ligação iônica", "Ligação covalente", "Pontes de hidrogênio", "Ligação peptídica" },
            correctIndex = 2,
            questionNumber = 14,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_014",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os pares de bases no DNA (A-T e G-C) são mantidos unidos por pontes de hidrogênio, que são interações fracas, mas altamente específicas. Adenina (A) se liga à Timina (T) por duas pontes de hidrogênio, enquanto Guanina (G) se liga à Citosina (C) por três pontes de hidrogênio." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a função principal do DNA?",
            answers = new string[] { "Transporte de moléculas", "Síntese de proteínas", "Armazenamento de informação genética", "Catálise de reações" },
            correctIndex = 2,
            questionNumber = 15,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_015",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O DNA (ácido desoxirribonucleico) tem como função principal armazenar a informação genética necessária para o desenvolvimento, funcionamento e reprodução dos organismos vivos. Essa informação está codificada na sequência de nucleotídeos." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a função principal do RNA?",
            answers = new string[] { "Transporte de moléculas", "Síntese de proteínas", "Armazenamento de informação genética", "Expressão da informação genética" },
            correctIndex = 3,
            questionNumber = 16,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_016",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA não armazena a informação genética de forma estável como o DNA, mas é essencial na expressão da informação genética, permitindo que os genes sejam expressos ao nível de proteínas." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que é desnaturação do DNA?",
            answers = new string[] {
                "Quebra da dupla hélice.",
                "Separação das fitas.",
                "Mudança na seqüência de bases.",
                "Todas as alternativas acima."
            },
            correctIndex = 1,
            questionNumber = 17,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_017",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A desnaturação do DNA ocorre quando as duas fitas da dupla hélice se separam devido à quebra das ligações de hidrogênio que mantêm os pares de bases unidos. Esse processo pode ser induzido por calor, variações de pH ou agentes químicos. A desnaturação não altera a sequência de bases (ou seja, não muda a informação genética), apenas rompe a estrutura helicoidal, deixando as fitas simples disponíveis." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que é renaturação do DNA?",
            answers = new string[] {
                "Formação de novas fitas.",
                "Reassociação das fitas.",
                "Replicação do DNA.",
                "Transcrição do DNA."
            },
            correctIndex = 1,
            questionNumber = 18,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_018",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A renaturação do DNA é o processo inverso da desnaturação. Após as fitas simples de DNA terem sido separadas (por calor, agentes químicos ou biológicos), elas podem se reassociar espontaneamente quando as condições normais são restabelecidas (temperatura adequada, pH equilibrado). Nesse processo, as bases complementares voltam a formar ligações de hidrogênio, reconstruindo a dupla hélice original." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que causa a desnaturação do DNA?",
            answers = new string[] {
                "Altas temperaturas",
                "Extremos de pH",
                "Ação de enzimas",
                "Todas as alternativas acima"
            },
            correctIndex = 3,
            questionNumber = 19,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_019",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A desnaturação do DNA pode ser causada por diferentes fatores que rompem as ligações de hidrogênio entre as bases complementares, levando à separação das fitas. Citando alguns desses fatores, temos que a desnaturação pode ocorrer por altas temperaturas (o calor fornece energia suficiente para quebrar as interações fracas entre as bases); por extremos de pH (alterações muito ácidas ou muito básicas desestabilizam as ligações de hidrogênio e a estrutura helicoidal); e por ação enzimática (enzimas, como helicases, promovem a separação das fitas durante processos celulares)." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Para que serve a medida de absorvância a 260nm?",
            answers = new string[] {
                "Medida da concentração de proteínas.",
                "Medida da concentração de ácidos nucléicos.",
                "Medida da temperatura de fusão do DNA.",
                "Medida da viscosidade de uma solução."
            },
            correctIndex = 1,
            questionNumber = 20,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_020",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A absorvância a 260 nm é utilizada em espectrofotometria para quantificar ácidos nucléicos (DNA e RNA). Isso ocorre porque as bases nitrogenadas presentes nessas moléculas possuem anéis aromáticos que absorvem fortemente luz ultravioleta nessa faixa de comprimento de onda. Assim, quanto maior a absorvância registrada, maior a concentração de ácidos nucléicos na amostra." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que é a regra de Chargaff?",
            answers = new string[] {
                "A = T e G = C",
                "A = G e T = C",
                "A = C e G = T",
                "Não há regra de Chargaff."
            },
            correctIndex = 0,
            questionNumber = 21,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_021",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A regra de Chargaff estabelece que, em qualquer molécula de DNA, a quantidade de adenina (A) é igual à de timina (T), e a quantidade de guanina (G) é igual à de citosina (C)." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Em que tipo de molécula a regra de Chargaff se aplica?",
            answers = new string[] {
                "DNA",
                "RNA",
                "Proteínas",
                "Carboidratos"
            },
            correctIndex = 0,
            questionNumber = 22,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_022",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A regra de Chargaff se aplica especificamente ao DNA, pois descreve a proporção entre as bases nitrogenadas adenina, timina, citosina e guanina." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que é o 'fluxo da informação genética'?",
            answers = new string[] {
                "O movimento de íons através da membrana.",
                "A replicação do DNA.",
                "O processo de conversão da informação genética em proteínas.",
                "O transporte de proteínas para o exterior da célula."
            },
            correctIndex = 2,
            questionNumber = 23,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_023",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O chamado “fluxo da informação genética” descreve o caminho pelo qual a informação contida no DNA é usada para produzir proteínas. Esse fluxo abrange diferentes processos, como replicação do DNA, transcrição, tradução e transcrição reversa." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual tipo de RNA transporta aminoácidos para os ribossomos?",
            answers = new string[] { "tRNA", "rRNA", "mRNA", "snRNA" },
            correctIndex = 0,
            questionNumber = 24,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_024",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA transportador (tRNA) é responsável por levar os aminoácidos até os ribossomos (composto por rRNA - RNA ribossomal - e proteínas ribossomais), onde ocorre a tradução do RNA mensageiro (mRNA) em proteínas. Cada tRNA possui um anticódon complementar ao códon do mRNA e carrega o aminoácido correspondente, garantindo que a sequência genética seja traduzida corretamente em uma cadeia polipeptídica." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual tipo de RNA faz parte da estrutura dos ribossomos?",
            answers = new string[] { "tRNA", "rRNA", "mRNA", "snRNA" },
            correctIndex = 1,
            questionNumber = 25,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_025",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA ribossomal (rRNA) é o principal componente estrutural e funcional dos ribossomos, que são responsáveis pela síntese de proteínas. Ele se associa a proteínas ribossomais para formar as duas subunidades (maior e menor) do ribossomo. Além de estrutural, o rRNA também desempenha papel catalítico, participando da formação das ligações peptídicas durante a tradução." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a principal diferença química entre DNA e RNA?",
            answers = new string[] { "Açúcar", "Bases nitrogenadas", "Grupamento fosfato", "Sequência de bases" },
            correctIndex = 0,
            questionNumber = 26,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_026",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A principal diferença química entre DNA e RNA está no tipo de açúcar presente em seus nucleotídeos. Enquanto o DNA contém desoxirribose (que possui um hidrogênio (H) no carbono 2'), o RNA contém ribose (que possui um grupo hidroxila (OH) no carbono 2')." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a principal diferença na composição de bases entre DNA e RNA?",
            answers = new string[] { "Timina vs. Uracila", "Adenina vs. Guanina", "Citosina vs. Guanina", "Ribose vs. Desoxirribose" },
            correctIndex = 0,
            questionNumber = 27,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_027",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Tanto o RNA quanto o DNA apresentam as bases adenina (A), citosina (C) e guanina (G). Porém, não é comum encontrar a uracila (U) no DNA e não é comum encontrar a timina (T) no RNA. Portanto, dizemos que a principal diferença na composição de bases entre DNA e RNA é que o DNA possui a base timina, enquanto o RNA apresenta uracila em seu lugar." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que é um códon?",
            answers = new string[] {
                "Uma seqüência de três bases no tRNA.",
                "Uma seqüência de três bases no mRNA.",
                "Uma seqüência de três bases no rRNA.",
                "Uma seqüência de três bases no DNA."
            },
            correctIndex = 1,
            questionNumber = 28,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_028",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Um códon é uma sequência de três bases nitrogenadas presente no RNA mensageiro (mRNA) que contém a informação necessária para a adição de um aminoácido durante a síntese de proteínas. Cada códon corresponde a um aminoácido específico ou a sinais de início e término da tradução, sendo fundamental para a expressão gênica." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a função do anticódon no tRNA?",
            answers = new string[] {
                "Ligar-se ao ribossomo.",
                "Ligar-se ao mRNA.",
                "Ligar-se a proteínas.",
                "Ligar-se ao DNA."
            },
            correctIndex = 1,
            questionNumber = 29,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_029",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O anticódon é uma sequência de três bases nitrogenadas presente no RNA transportador (tRNA) cuja função é reconhecer e ligar-se de forma complementar ao códon do RNA mensageiro (mRNA) durante a síntese de proteínas. Essa interação garante que o aminoácido correto seja incorporado à cadeia polipeptídica em formação, assegurando a fidelidade da tradução genética." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual a função principal dos rRNAs?",
            answers = new string[] {
                "Transporte de aminoácidos.",
                "Síntese de proteínas.",
                "Fazem parte da estrutura dos ribossomos.",
                "Catalisam reações."
            },
            correctIndex = 2,
            questionNumber = 30,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_030",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os rRNAs (RNAs ribossomais) são componentes essenciais dos ribossomos, formando junto com proteínas ribossomais as subunidades maior e menor. Além de fornecerem a estrutura física dos ribossomos, eles também desempenham papel catalítico na síntese de proteínas, funcionando como ribozimas que catalisam a formação das ligações peptídicas." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Quais são os três componentes de um nucleotídeo?",
            answers = new string[] { "Açúcar, base, fosfato", "Açúcar, base, aminoácido", "Base, aminoácido, fosfato", "Açúcar, lipídeo, base" },
            correctIndex = 0,
            questionNumber = 31,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_031",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os nucleotídeos são as unidades básicas que formam os ácidos nucleicos, como o DNA e o RNA. Cada nucleotídeo é composto por três partes fundamentais: um açúcar de cinco carbonos (pentose); uma base nitrogenada; e um ou mais fosfatos." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O que é um nucleosídeo?",
            answers = new string[] { "Açúcar + base + fosfato", "Açúcar + base", "Base + fosfato", "Açúcar + aminoácido" },
            correctIndex = 1,
            questionNumber = 32,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_032",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Um nucleosídeo é formado pela união de uma pentose (açúcar, que pode ser ribose no RNA ou desoxirribose no DNA) com uma base nitrogenada (adenina, guanina, citosina, timina ou uracila). Quando ao nucleosídeo se adiciona um grupo fosfato, ele passa a ser chamado de nucleotídeo, que é a unidade dos ácidos nucléicos." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual o açúcar presente nos ribonucleotídeos?",
            answers = new string[] { "Desoxirribose", "Ribose", "Glicose", "Frutose" },
            correctIndex = 1,
            questionNumber = 33,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_033",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Nos ribonucleotídeos, que são os “blocos de construção” do RNA, o açúcar presente é a ribose. Essa pentose possui um grupo hidroxila (-OH) ligado ao carbono 2’, o que a diferencia da desoxirribose encontrada nos nucleotídeos do DNA, que tem apenas um hidrogênio nesse carbono." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual o açúcar presente nos desoxirribonucleotídeos?",
            answers = new string[] { "Desoxirribose", "Ribose", "Glicose", "Frutose" },
            correctIndex = 0,
            questionNumber = 34,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "nucleicAcids_034",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Nos desoxirribonucleotídeos, que são os “blocos de construção” do DNA, o açúcar presente é a desoxirribose. A diferença fundamental em relação à ribose (presente nos ribonucleotídeos do RNA) é que a desoxirribose possui apenas um hidrogênio (H) no carbono 2’, enquanto a ribose possui um grupo hidroxila (-OH) nesse mesmo carbono." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Os ácidos nucleicos são polímeros formados por unidades chamadas:",
            answers = new string[] {
                "Aminoácidos",
                "Nucleotídeos",
                "Monossacarídeos",
                "Lipídios"
            },
            correctIndex = 1,
            questionNumber = 35,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_035",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os ácidos nucleicos, como DNA e RNA, são polímeros formados pela repetição de unidades chamadas nucleotídeos. Cada nucleotídeo é composto por: um açúcar pentose (ribose no RNA e desoxirribose no DNA), uma base nitrogenada (adenina, guanina, citosina, timina ou uracila) e um ou mais grupos fosfato." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Quais são os dois principais tipos de ácidos nucleicos encontrados nos seres vivos?",
            answers = new string[] {
                "DNA e RNA",
                "DNA e ATP",
                "RNA e lipídios",
                "DNA e proteínas"
            },
            correctIndex = 0,
            questionNumber = 36,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_036",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Ácidos nucleicos são polímeros de nucleotídeos. Desoxirribonucleotídeos constituem moléculas de DNA (ácido desoxirribonucleico) e ribonucleotídeos constituem moléculas de RNA (ácido ribonucleico), sendo estes dois os principais tipos de ácidos nucleicos encontrados nos seres vivos." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O açúcar presente no RNA é:",
            answers = new string[] {
                "Desoxirribose",
                "Glicose",
                "Ribose",
                "Maltose"
            },
            correctIndex = 2,
            questionNumber = 37,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_037",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Nos ribonucleotídeos, que são os “blocos de construção” do RNA, o açúcar presente é a ribose. Essa pentose possui um grupo hidroxila (-OH) ligado ao carbono 2’, o que a diferencia da desoxirribose encontrada nos nucleotídeos do DNA." }
        },
         new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "No DNA, a adenina sempre se emparelha com:",
            answers = new string[] {
                "Guanina",
                "Citosina",
                "Timina",
                "Uracila"
            },
            correctIndex = 2,
            questionNumber = 38,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_038",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "No DNA, as bases nitrogenadas da dupla fita pareiam por meio de ligações de hidrogênio, formando pares complementares. A adenina (A) sempre se emparelha com a timina (T), enquanto a citosina (C) se emparelha com a guanina (G). O correto emparelhamento é fundamental para manter a estrutura da molécula de DNA e evitar mutações durante sua replicação." }
        },
         new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "A estrutura de dupla hélice do DNA foi proposta por:",
            answers = new string[] {
                "Darwin e Lamarck",
                "Watson e Crick",
                "Pasteur e Koch",
                "Franklin e Mendel"
            },
            correctIndex = 1,
            questionNumber = 39,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_039",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura de dupla hélice do DNA foi proposta em 1953 por James Watson e Francis Crick, que descreveram como duas fitas de nucleotídeos se enrolam em espiral em torno do mesmo eixo, mantidas juntas por ligações de hidrogênio entre bases complementares (adenina-timina e guanina-citosina). Essa descoberta revolucionou a biologia, pois explicou de forma elegante como a informação genética poderia ser armazenada e replicada com fidelidade. Embora Watson e Crick tenham sido os responsáveis pela proposta final, é importante reconhecer a contribuição crucial de Rosalind Franklin, cujas imagens de difração de raios X forneceram evidências fundamentais para o modelo da dupla hélice." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O RNA que leva a informação genética do DNA até os ribossomos chama-se:",
            answers = new string[] {
                "RNA ribossômico (rRNA)",
                "RNA transportador (tRNA)",
                "RNA mensageiro (mRNA)",
                "RNA nuclear"
            },
            correctIndex = 2,
            questionNumber = 40,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_040",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O mRNA (RNA mensageiro) é o tipo de RNA responsável por levar a informação genética contida no DNA até os ribossomos, onde ocorre a síntese de proteínas." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual base nitrogenada é exclusiva do RNA e substitui a timina do DNA?",
            answers = new string[] {
                "Guanina",
                "Uracila",
                "Adenina",
                "Citosina"
            },
            correctIndex = 1,
            questionNumber = 41,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_041",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "No RNA, a base nitrogenada uracila substitui a timina presente no DNA, mantendo o emparelhamento com a adenina. Essa é uma das características que distinguem RNA e DNA." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O processo de síntese de RNA a partir de DNA é chamado de:",
            answers = new string[] {
                "Tradução",
                "Transcrição",
                "Replicação",
                "Mutação"
            },
            correctIndex = 1,
            questionNumber = 42,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_042",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A transcrição é o processo biológico em que a informação genética contida no DNA é utilizada para produzir uma molécula de RNA. Nesse processo, uma das fitas do DNA serve de molde para a formação do RNA, principalmente do RNA mensageiro (mRNA), que posteriormente participa da síntese de proteínas. Esse mecanismo é essencial para a expressão gênica, permitindo que as informações armazenadas no DNA sejam utilizadas pelas células." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O nucleotídeo ATP é conhecido principalmente por:",
            answers = new string[] {
                "Formar a bicamada lipídica",
                "Ser uma fonte de energia celular",
                "Carregar oxigênio no sangue",
                "Transportar aminoácidos"
            },
            correctIndex = 1,
            questionNumber = 43,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_043",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O ATP (adenosina trifosfato) é o principal nucleotídeo responsável pelo armazenamento e fornecimento de energia para as atividades celulares. Ele funciona como uma “moeda energética” da célula. Quando uma de suas ligações fosfato é quebrada, a energia antes contida na ligação pode ser utilizada nos processos metabólicos, como transporte de substâncias, contração muscular e síntese de moléculas." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O nucleotídeo ATP é conhecido principalmente por:",
            answers = new string[] {
                "Formar a bicamada lipídica",
                "Ser uma fonte de energia celular",
                "Carregar oxigênio no sangue",
                "Transportar aminoácidos"
            },
            correctIndex = 1,
            questionNumber = 44,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_044",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O ATP (adenosina trifosfato) é o principal nucleotídeo responsável pelo armazenamento e fornecimento de energia para as atividades celulares. Ele funciona como uma “moeda energética” da célula. Quando uma de suas ligações fosfato é quebrada, a energia antes contida na ligação pode ser utilizada nos processos metabólicos, como transporte de substâncias, contração muscular e síntese de moléculas." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Durante a replicação do DNA, a enzima responsável por unir os nucleotídeos é a:",
            answers = new string[] {
                "DNA polimerase",
                "RNA polimerase",
                "Ligase",
                "Transcriptase reversa"
            },
            correctIndex = 0,
            questionNumber = 45,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_045",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Durante a replicação do DNA, a enzima DNA polimerase é responsável pelo crescimento da nova fita de DNA. Ela catalisa adição de nucleotídeos complementares à fita molde à extremidade 3’ livre de uma fita de DNA, por causa disso, dizemos que a nova fita cresce no sentido 5’ → 3’. Por consequência, durante a replicação, na fita molde de sentido 5’ → 3’, são formados fragmentos de DNA que posteriormente são unidos pela enzima ligase." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Os ácidos nucleicos são macromoléculas formadas por unidades chamadas:",
            answers = new string[] {
                "Aminoácidos",
                "Nucleotídeos",
                "Monossacarídeos",
                "Lipídeos"
            },
            correctIndex = 1,
            questionNumber = 46,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_046",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os ácidos nucleicos, como DNA e RNA, são macromoléculas formadas pela repetição de unidades chamadas nucleotídeos, cada um composto por uma pentose (ribose no RNA ou desoxirribose no DNA), uma base nitrogenada e um ou mais grupos fosfato." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Um nucleotídeo é composto por:",
            answers = new string[] {
                "Pentose + fosfato + base nitrogenada",
                "Hexose + lipídio + aminoácido",
                "Glicose + fosfato + proteína",
                "Glicerol + base nitrogenada + ácido graxo"
            },
            correctIndex = 0,
            questionNumber = 47,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_047",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Um nucleotídeo é formado por três componentes principais: uma pentose (ribose no RNA ou desoxirribose no DNA), um grupo fosfato com papel na ligação entre nucleotídeos e uma base nitrogenada (adenina, timina, citosina, guanina e uracila), sendo essa estrutura fundamental para compor os ácidos nucleicos e permitir o armazenamento, transmissão e expressão da informação genética." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "A base nitrogenada presente apenas no RNA é:",
            answers = new string[] {
                "Timina",
                "Citosina",
                "Uracila",
                "Adenina"
            },
            correctIndex = 2,
            questionNumber = 48,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_048",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A uracila (U) é uma base nitrogenada encontrada exclusivamente no RNA, substituindo a timina (T), que está presente no DNA. No RNA, a uracila faz pareamento com a adenina durante os processos de transcrição e tradução." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "A base nitrogenada presente apenas no DNA é:",
            answers = new string[] {
                "Uracila",
                "Adenina",
                "Timina",
                "Guanina"
            },
            correctIndex = 2,
            questionNumber = 49,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_049",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A timina (T) é uma base nitrogenada encontrada exclusivamente no DNA. Ela substitui a uracila (U), que está presente no RNA. No DNA, a timina faz pareamento com a adenina (A), seguindo a regra de complementaridade das bases nitrogenadas." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "A molécula de DNA tem a forma característica conhecida como:",
            answers = new string[] {
                "Hélice simples",
                "Tripla hélice",
                "Dupla hélice",
                "Cadeia linear"
            },
            correctIndex = 2,
            questionNumber = 50,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_050",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A molécula de DNA, em pH fisiológico, apresenta como estrutura tridimensional mais estável a forma de dupla hélice, na qual duas fitas polinucleotídicas se enrolam uma em torno da outra, como uma “escada torcida”. Essas fitas são antiparalelas e mantidas juntas por ligações de hidrogênio entre bases nitrogenadas complementares (adenina com timina e citosina com guanina). Esse modelo estrutural foi proposto por James Watson e Francis Crick, com contribuições importantes de dados de difração de raios X obtidos por Rosalind Franklin." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "A pentose presente no DNA é:",
            answers = new string[] {
                "Ribose",
                "Desoxirribose",
                "Glicose",
                "Frutose"
            },
            correctIndex = 1,
            questionNumber = 51,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_051",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O DNA possui como um de seus componentes estruturais uma pentose chamada desoxirribose, um açúcar de cinco carbonos que difere da ribose pela ausência de um átomo de oxigênio no carbono 2’. Essa pequena diferença estrutural é a principal distinção entre DNA e RNA." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "No pareamento de bases do DNA, a adenina sempre se liga à:",
            answers = new string[] {
                "Guanina",
                "Citosina",
                "Uracila",
                "Timina"
            },
            correctIndex = 3,
            questionNumber = 52,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_052",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "No DNA, o pareamento das bases nitrogenadas segue uma regra de complementaridade: a adenina (A) sempre se liga à timina (T) por meio de ligações de hidrogênio. Esse emparelhamento é fundamental para manter a estabilidade da estrutura da dupla hélice e garantir a correta transmissão da informação genética durante a replicação." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "A principal função do RNA mensageiro (RNAm) é:",
            answers = new string[] {
                "Formar a estrutura dos ribossomos",
                "Transportar aminoácidos",
                "Levar a informação genética do DNA até os ribossomos",
                "Catalisar reações químicas"
            },
            correctIndex = 2,
            questionNumber = 53,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_053",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA mensageiro (RNAm) é responsável por transportar a informação genética contida no DNA até os ribossomos, onde essa informação será utilizada na síntese de proteínas. Ele é produzido durante o processo de transcrição e funciona como uma “cópia” temporária do gene que será traduzido em proteína." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O RNA transportador (RNAt) tem como função:",
            answers = new string[] {
                "Levar aminoácidos até os ribossomos durante a síntese proteica",
                "Carregar energia química",
                "Armazenar informação genética",
                "Catalisar reações metabólicas"
            },
            correctIndex = 0,
            questionNumber = 54,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_054",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA transportador (tRNA) tem como função principal carregar os aminoácidos específicos e entregá-los aos ribossomos durante o processo de tradução. Cada RNAt possui um anticódon que reconhece um códon complementar no RNAm, garantindo a incorporação correta dos aminoácidos na proteína em formação." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Qual é a função principal do DNA nas células?",
            answers = new string[] {
                "Atuar como catalisador enzimático",
                "Fornecer energia imediata",
                "Armazenar e transmitir a informação genética",
                "Transportar oxigênio"
            },
            correctIndex = 2,
            questionNumber = 55,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_055",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O DNA tem como função principal guardar de forma estável a informação genética das células e garantir sua transmissão de uma geração para outra." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Os ácidos nucleicos são formados por unidades chamadas:",
            answers = new string[] {
                "Aminoácidos",
                "Monossacarídeos",
                "Nucleotídeos",
                "Ácidos graxos"
            },
            correctIndex = 2,
            questionNumber = 56,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_056",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os ácidos nucleicos, como DNA e RNA, são macromoléculas formadas pela repetição de unidades chamadas nucleotídeos, cada um composto por uma pentose (ribose ou desoxirribose), uma base nitrogenada e um ou mais grupos fosfato." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Cada nucleotídeo é composto por:",
            answers = new string[] {
                "Aminoácido, fosfato e água",
                "Açúcar, base nitrogenada e fosfato",
                "Glicerol, ácido graxo e base nitrogenada",
                "Açúcar, lipídio e proteína"
            },
            correctIndex = 1,
            questionNumber = 57,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_057",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Cada nucleotídeo é formado por três componentes fundamentais: uma molécula de açúcar pentose (ribose no RNA ou desoxirribose no DNA), uma base nitrogenada (adenina, timina, citosina, guanina ou uracila) e um ou mais grupos fosfato." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O DNA possui como açúcar:",
            answers = new string[] {
                "Glicose",
                "Ribose",
                "Desoxirribose",
                "Galactose"
            },
            correctIndex = 2,
            questionNumber = 58,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_058",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O DNA possui como açúcar a desoxirribose, uma pentose que difere da ribose presente no RNA por não ter um átomo de oxigênio no carbono 2’; essa diferença estrutural é fundamental para conferir maior estabilidade ao DNA, permitindo que ele funcione como molécula de armazenamento de informação genética a longo prazo, enquanto o RNA, mais instável, atua em processos temporários como transcrição e tradução." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O RNA possui como açúcar:",
            answers = new string[] {
                "Glicose",
                "Ribose",
                "Desoxirribose",
                "Maltose"
            },
            correctIndex = 1,
            questionNumber = 59,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_059",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA possui como açúcar a ribose, uma pentose que contém um grupo hidroxila (-OH) no carbono 2’, tornando-o mais reativo e menos estável em comparação ao DNA, que possui desoxirribose. Essa diferença estrutural explica por que o RNA é adequado para funções temporárias, como transcrição e tradução, enquanto o DNA é mais estável e ideal para o armazenamento de longo prazo da informação genética." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Na estrutura de dupla hélice do DNA, as bases emparelham-se segundo a regra de Chargaff:",
            answers = new string[] {
                "A – G e C – T",
                "A – C e T – G",
                "A – T e C – G",
                "A – U e C – G"
            },
            correctIndex = 2,
            questionNumber = 60,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_060",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Na estrutura de dupla hélice do DNA, as bases nitrogenadas seguem a regra de Chargaff: a adenina (A) sempre se emparelha com a timina (T), e a citosina (C) sempre se emparelha com a guanina (G). Esse emparelhamento é possível graças às ligações de hidrogênio que estabilizam a dupla hélice e garantem a fidelidade da replicação do DNA." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O RNA mensageiro (RNAm) tem como função principal:",
            answers = new string[] {
                "Transportar aminoácidos",
                "Atuar como catalisador enzimático",
                "Levar a informação do DNA até os ribossomos",
                "Formar a dupla hélice do DNA"
            },
            correctIndex = 2,
            questionNumber = 61,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_061",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA mensageiro (RNAm) é responsável por transportar a informação genética contida no DNA até os ribossomos, onde essa informação será utilizada na síntese de proteínas." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "O RNA transportador (RNAt) é responsável por:",
            answers = new string[] {
                "Levar aminoácidos até o ribossomo durante a síntese de proteínas",
                "Duplicar o DNA",
                "Formar a membrana celular",
                "Produzir energia na respiração"
            },
            correctIndex = 0,
            questionNumber = 62,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_062",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O RNA transportador (RNAt) atua no processo de tradução, levando aminoácidos específicos até os ribossomos. Cada RNAt possui um anticódon que reconhece um códon correspondente no RNA mensageiro (RNAm), garantindo que os aminoácidos sejam posicionados na ordem correta para formar uma proteína." }
        },
        new Question {
            questionDatabankName = "NucleicAcidsQuestionDatabase",
            questionText = "Quem descreveu o modelo da dupla hélice do DNA em 1953?",
            answers = new string[] {
                "Darwin e Mendel",
                "Watson e Crick",
                "Franklin e Chargaff",
                "Pauling e Wöhler"
            },
            correctIndex = 1,
            questionNumber = 63,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "nucleicAcids_063",
            topic = "nucleicAcids",
            subtopic = null,
            displayName = "Ácidos Nucleicos",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O modelo da dupla hélice do DNA foi proposto em 1953 por James Watson e Francis Crick. Eles descreveram a estrutura do DNA como duas fitas antiparalelas enroladas em forma de hélice, com pareamento específico entre as bases nitrogenadas (adenina com timina e citosina com guanina)." }
        }
    };

    public List<Question> GetQuestions() => questions;

    public QuestionSet GetQuestionSetType() => QuestionSet.nucleicAcids;

    public string GetDatabankName()  => "NucleicAcidsQuestionDatabase";
    public string GetDisplayName()   => "Ácidos Nucleicos";

    public bool IsDatabaseInDevelopment() => databaseInDevelopment;
}