using System.Collections.Generic;
using QuestionSystem;

public class ProteinQuestionDatabase : IQuestionDatabase
{
    private bool databaseInDevelopment = false;
    
    private List<Question> questions = new List<Question>
    {
         new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "A = Ponte de Hidrogênio, B = Interação Eletrostática, C = Interação Hidrofóbica, D = Ponte Dissulfeto",
                "A = Ponte de Dissulfeto, B = Interação Eletrostática, C = Interação Hidrofóbica, D = Ponte de Hidrogênio",
                "A = Interação Hidrofóbica, B = Ponte de Hidrogênio, C = Ponte Dissulfeto, D = Interação Eletrostática",
                "A = Interação Eletrostática, B = Ponte de Hidrogênio, C = Interação Hidrofóbica, D = Ponte Dissulfeto",
            },
            correctIndex = 2,
            questionNumber = 1,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/proteinQuestion_1",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_001",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Que tipo de ligação une os aminoácidos na estrutura primária de uma proteína?",
            answers = new string[] {
                "Ligações de hidrogênio",
                "Ligações iônicas",
                "Ligações peptídicas",
                "Pontes dissulfeto"
            },
            correctIndex = 2,
            questionNumber = 2,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_002",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura primária de uma proteína é definida pela sequência linear de aminoácidos unidos entre si por ligações peptídicas. Essas ligações covalentes formam-se entre o grupo carboxila (-COOH) de um aminoácido e o grupo amino (-NH₂) do aminoácido seguinte, com a liberação de uma molécula de água — processo chamado de condensação ou desidratação. É justamente essa sequência de aminoácidos, determinada geneticamente, que define a identidade de cada proteína e serve de base para todos os níveis superiores de sua estrutura tridimensional." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A formação de uma ligação peptídica envolve:",
            answers = new string[] {
                "A união de dois aminoácidos com a perda de uma molécula de água.",
                "A união de dois aminoácidos com a adição de uma molécula de água.",
                "A união de três aminoácidos com a perda de uma molécula de água.",
                "A união de três aminoácidos com a adição de uma molécula de água."
            },
            correctIndex = 0,
            questionNumber = 3,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_003",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A ligação peptídica é formada por uma reação de condensação entre dois aminoácidos: o grupo carboxila (-COOH) de um aminoácido reage com o grupo amino (-NH₂) do outro, resultando na formação de uma ligação covalente do tipo -CO-NH- e na liberação de uma molécula de água. Esse processo é repetido sucessivamente durante a síntese proteica nos ribossomos, encadeando os aminoácidos em uma sequência linear que constituirá a estrutura primária da proteína. A reação inversa — a quebra da ligação peptídica pela adição de água — é chamada de hidrólise e é catalisada pelas proteases." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Identifique abaixo o aminoácido que pode formar pontes dissulfeto em proteínas",
            answers = new string[] {
                "AnswerImages/AminoacidsDB/cisteina",
                "AnswerImages/AminoacidsDB/treonina",
                "AnswerImages/AminoacidsDB/alanina",
                "AnswerImages/AminoacidsDB/fenilalanina"
            },
            correctIndex = 0,
            questionNumber = 4,
            answerType = AnswerType.Image,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_004",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Que tipo de estrutura protéica é formada pela união de duas ou mais cadeias polipeptídicas?",
            answers = new string[] {
                "Primária",
                "Secundária",
                "Terciária",
                "Quaternária"
            },
            correctIndex = 3,
            questionNumber = 5,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_005",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura quaternária é o nível de organização proteica que envolve a associação de duas ou mais cadeias polipeptídicas — chamadas de subunidades — mantidas juntas por interações não covalentes, como pontes de hidrogênio, interações hidrofóbicas e interações eletrostáticas, e eventualmente por pontes dissulfeto. Nem todas as proteínas possuem estrutura quaternária; ela está presente apenas naquelas compostas por múltiplas subunidades. Um exemplo clássico é a hemoglobina, formada por quatro subunidades polipeptídicas, cuja associação é essencial para sua função de transporte de oxigênio." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Uma estrutura formada basicamente por alfa-hélices",
                "Uma estrutura formada basicamente por fitas-betas",
                "A imagem representa apenas a estrutura primária de uma proteína",
                "Não há estrutura definida",
            },
            correctIndex = 0,
            questionNumber = 6,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/proteinQuestion_6",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_006",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Quais são os principais elementos de estrutura secundária?",
            answers = new string[] {
                "Alfa-hélices e fitas-betas",
                "Alfa-hélices e pontes dissulfeto",
                "Fitas-betas e ligações peptídicas",
                "Voltas e ligações iônicas"
            },
            correctIndex = 0,
            questionNumber = 7,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_007",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura secundária de uma proteína refere-se aos padrões regulares e repetitivos de dobramento local da cadeia polipeptídica, estabilizados principalmente por pontes de hidrogênio entre os grupos da cadeia principal (carbonila e amida). Os dois elementos mais comuns são a alfa-hélice, em que a cadeia se enrola em espiral com pontes de hidrogênio intracadeia, e a fita beta, em que segmentos estendidos da cadeia se alinham lado a lado formando uma estrutura em folha pregueada. Esses elementos constituem os blocos estruturais fundamentais que, combinados, darão origem à estrutura tridimensional completa da proteína." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Interações hidrofóbicas",
                "Pontes de hidrogênio",
                "Ligações iônicas",
                "Pontes dissulfeto"
            },
            correctIndex = 1,
            questionNumber = 8,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/proteinQuestion_8",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_008",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/AminoacidsDB/acido_aspartico",
                "AnswerImages/AminoacidsDB/glutamina",
                "AnswerImages/AminoacidsDB/arginina",
                "AnswerImages/AminoacidsDB/prolina"
            },
            correctIndex = 3,
            questionNumber = 9,
            answerType = AnswerType.Image,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/proteinQuestion_9",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_009",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A estrutura terciária de uma proteína se refere a:",
            answers = new string[] {
                "Seqüência de aminoácidos.",
                "Arranjo espacial de alfa-hélices e folhas beta.",
                "Interações entre diferentes cadeias polipeptídicas.",
                "Estrutura tridimensional de uma sequência de aminoácidos."
            },
            correctIndex = 3,
            questionNumber = 10,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_010",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura terciária corresponde ao arranjo tridimensional completo de uma única cadeia polipeptídica, resultante do dobramento de todos os seus elementos de estrutura secundária (alfa-hélices, fitas beta e voltas) no espaço. Esse dobramento é determinado principalmente pelas interações entre as cadeias laterais (grupos R) dos aminoácidos ao longo da cadeia e é estabilizado por pontes de hidrogênio, interações hidrofóbicas, interações iônicas e pontes dissulfeto. A estrutura terciária define a forma globular ou fibrosa final da proteína e é essencial para sua função biológica." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Quais forças mantêm a estrutura terciária de uma proteína?",
            answers = new string[] {
                "Apenas ligações peptídicas.",
                "Pontes de hidrogênio, interações hidrofóbicas, interações iônicas e pontes dissulfeto.",
                "Apenas pontes dissulfeto.",
                "Apenas ligações de hidrogênio."
            },
            correctIndex = 1,
            questionNumber = 11,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "proteins_011",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura terciária de uma proteína é mantida por um conjunto de interações entre as cadeias laterais dos aminoácidos: pontes de hidrogênio formadas entre grupos polares; interações hidrofóbicas que agrupam resíduos apolares no interior da proteína, longe do solvente aquoso; interações iônicas (ou eletrostáticas) entre resíduos de cargas opostas; e pontes dissulfeto, que são ligações covalentes formadas entre dois resíduos de cisteína. Nenhuma dessas forças, isoladamente, seria suficiente para estabilizar a estrutura — é a combinação de todas elas que confere estabilidade e especificidade ao dobramento proteico." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Identifique abaixo a melhor representação de estrutura secundaria",
            answers = new string[] {
                "AnswerImages/ProteinDB/estrutura_primaria",
                "AnswerImages/ProteinDB/estrutura_secundaria",
                "AnswerImages/ProteinDB/estrutura_terciaria",
                "AnswerImages/ProteinDB/estrutura_quaternaria"
            },
            correctIndex = 1,
            questionNumber = 12,
            answerType = AnswerType.Image,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_012",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/AminoacidsDB/acido_aspartico",
                "AnswerImages/AminoacidsDB/treonina",
                "AnswerImages/AminoacidsDB/arginina",
                "AnswerImages/AminoacidsDB/isoleucina"
            },
            correctIndex = 3,
            questionNumber = 13,
            answerType = AnswerType.Image,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/proteinQuestion_13",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_013",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "AnswerImages/AminoacidsDB/triptofano",
                "AnswerImages/AminoacidsDB/isoleucina",
                "AnswerImages/AminoacidsDB/arginina",
                "AnswerImages/AminoacidsDB/fenilalanina"
            },
            correctIndex = 2,
            questionNumber = 14,
            answerType = AnswerType.Image,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/proteinQuestion_14",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_014",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Identifique abaixo a melhor representação de estrutura quaternaria",
            answers = new string[] {
                "AnswerImages/ProteinDB/estrutura_primaria",
                "AnswerImages/ProteinDB/estrutura_secundaria",
                "AnswerImages/ProteinDB/estrutura_terciaria",
                "AnswerImages/ProteinDB/estrutura_quaternaria"
            },
            correctIndex = 3,
            questionNumber = 15,
            answerType = AnswerType.Image,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_015",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Identifique abaixo a melhor representação de estrutura primaria",
            answers = new string[] {
                "AnswerImages/ProteinDB/estrutura_primaria",
                "AnswerImages/ProteinDB/estrutura_secundaria",
                "AnswerImages/ProteinDB/estrutura_terciaria",
                "AnswerImages/ProteinDB/estrutura_quaternaria"
            },
            correctIndex = 0,
            questionNumber = 16,
            answerType = AnswerType.Image,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_016",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Identifique abaixo a melhor representação de estrutura terciária",
            answers = new string[] {
                "AnswerImages/ProteinDB/estrutura_primaria",
                "AnswerImages/ProteinDB/estrutura_secundaria",
                "AnswerImages/ProteinDB/estrutura_terciaria",
                "AnswerImages/ProteinDB/estrutura_quaternaria"
            },
            correctIndex = 2,
            questionNumber = 17,
            answerType = AnswerType.Image,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_017",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
         new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "alfa-hélices",
                "fitas-beta",
                "folhas-beta",
                "beta-hélices",
            },
            correctIndex = 0,
            questionNumber = 18,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/proteinQuestion_19",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_018",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "alfa-hélices",
                "fitas-beta",
                "fitas-alfa",
                "beta-hélices",
            },
            correctIndex = 1,
            questionNumber = 19,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/proteinQuestion_20",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_019",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Cromatografia de focalização isoelétrica",
                "Cromatografia de gel filtração",
                "Cromatrografia de troca iônica",
                "Cromatrografia de afinidade",
            },
            correctIndex = 2,
            questionNumber = 20,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/methodsQuestions20",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_020",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Cromatografia de focalização isoelétrica",
                "Cromatografia de gel filtração",
                "Cromatrografia de troca iônica",
                "Cromatrografia de afinidade",
            },
            correctIndex = 1,
            questionNumber = 21,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/methodsQuestions21",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_021",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Imagine uma mistura de duas proteínas (15 kDa e 45 kDa). Usando uma coluna de exclusão que interage com proteínas de até 20 kDa, qual proteína sairá primeiro da coluna?",
            answers = new string[] {
                "Ambas saírão juntas",
                "12 kDa sairá primeiro",
                "45 kDa sairá primeiro",
                "A coluna não conseguirá separar as proteínas",
            },
            correctIndex = 2,
            questionNumber = 22,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_022",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Na cromatografia de exclusão por tamanho (gel filtração), as proteínas são separadas com base em seu tamanho molecular. Proteínas menores que o limite de corte da coluna conseguem penetrar nos poros da matriz e percorrem um caminho mais longo, sendo retidas por mais tempo e eluindo mais tarde. Proteínas maiores que esse limite não entram nos poros, percorrem apenas o volume externo da coluna e eluem primeiro. Nesse caso, a proteína de 45 kDa — maior que o limite de 20 kDa da coluna — não interage com a matriz e sai primeiro, enquanto a de 15 kDa entra nos poros e é retida por mais tempo." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Imagine uma mistura de duas proteínas com pI = 6 e pI = 12. Usando uma coluna trocadora de cátions, qual proteína sairá primeiro da coluna com uma fase móvel com pH = 9?",
            answers = new string[] {
                "Ambas saírão juntas",
                "Proteína com pI = 6 sairá primeiro",
                "Proteína com pI = 9 sairá primeiro",
                "A coluna não conseguirá separar as proteínas",
            },
            correctIndex = 1,
            questionNumber = 23,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "proteins_023",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Em uma coluna trocadora de cátions, a matriz possui carga negativa e retém proteínas com carga líquida positiva. A carga líquida de uma proteína depende da relação entre o pH do meio e seu ponto isoelétrico (pI): quando o pH do meio é maior que o pI, a proteína carrega carga líquida negativa e não é retida; quando o pH é menor que o pI, a proteína carrega carga líquida positiva e se liga à coluna. Com fase móvel a pH 9, a proteína de pI = 6 está em meio mais básico que seu pI, portanto tem carga negativa e não interage com a coluna, eluindo primeiro. Já a proteína de pI = 12 está em meio mais ácido que seu pI, tem carga positiva e fica retida na coluna." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A técnica de eletroforese SDS-Page separa proteínas com base em:",
            answers = new string[] {
                "Seu tamanho.",
                "Sua carga líquida.",
                "Sua sequência de aminoácidos.",
                "Sua estrutura terciária."
            },
            correctIndex = 0,
            questionNumber = 24,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "proteins_024",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Na eletroforese SDS-PAGE, as proteínas são tratadas com dodecil sulfato de sódio (SDS), um detergente que se liga à cadeia polipeptídica em proporção ao seu tamanho, conferindo a todas as proteínas uma carga negativa uniforme e proporcional à sua massa. Isso elimina as diferenças de carga natural entre as proteínas, de modo que a separação no gel de poliacrilamida ocorre exclusivamente com base no tamanho molecular: proteínas menores migram mais rapidamente e percorrem maior distância no gel, enquanto as maiores ficam mais próximas do ponto de aplicação." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Em eletroforese com focalização isoelétrica, um aminoácido com carga líquida positiva migrará para o pólo:",
            answers = new string[] {
                "Positivo",
                "Negativo",
                "Não migrará",
                "Depende do pH"
            },
            correctIndex = 1,
            questionNumber = 25,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "proteins_025",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Em eletroforese, cargas opostas se atraem: uma molécula com carga líquida positiva é atraída pelo polo negativo (cátodo) e migra em sua direção. Na focalização isoelétrica, o gel apresenta um gradiente de pH, e a molécula migra até atingir a região onde o pH é igual ao seu ponto isoelétrico (pI), momento em que sua carga líquida se torna zero e a migração cessa. Até atingir essa região, porém, uma molécula positivamente carregada se move em direção ao polo negativo." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Em eletroforese com focalização isoelétrica, um aminoácido com carga líquida negativa migrará para o pólo:",
            answers = new string[] {
                "Negativo",
                "Positivo",
                "Não migrará",
                "Depende do pH"
            },
            correctIndex = 1,
            questionNumber = 26,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "proteins_026",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Uma molécula com carga líquida negativa é repelida pelo polo negativo e atraída pelo polo positivo (ânodo), migrando em sua direção durante a eletroforese. Na focalização isoelétrica, esse deslocamento continua até que a molécula alcance a região do gradiente de pH correspondente ao seu ponto isoelétrico (pI), onde sua carga líquida se anula e a migração é interrompida. Esse princípio permite separar proteínas com grande precisão com base em seus pIs, mesmo quando possuem massas moleculares semelhantes." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Em eletroforese com focalização isoelétrica, um aminoácido no seu ponto isoelétrico:",
            answers = new string[] {
                "Migrará para o pólo positivo.",
                "Migrará para o pólo negativo.",
                "Não migrará.",
                "Migrará para ambos os pólos."
            },
            correctIndex = 2,
            questionNumber = 27,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "proteins_027",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O ponto isoelétrico (pI) é o valor de pH no qual uma molécula possui carga líquida igual a zero, ou seja, o número de cargas positivas e negativas é exatamente igual. Sem carga líquida, a molécula não sofre atração nem repulsão pelo campo elétrico aplicado na eletroforese e, portanto, não migra em nenhuma direção. Na focalização isoelétrica, esse é justamente o ponto onde cada proteína se estabiliza ao longo do gradiente de pH do gel, permitindo sua identificação e separação com alta resolução." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "A curva na cor vermelha refere-se a uma proteína",
                "A curva na cor azul refere-se a uma proteína",
                "A curva na cor vermelha refere-se ao aminoácido alanina",
                "A curva na cor azul refere-se ao aminoácido leucina"
            },
            correctIndex = 1,
            questionNumber = 28,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/methodsQuestions28",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_028",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Transportar oxigênio",
                "Manter estrutura das hemácias",
                "Contração dos pulmões",
                "Armazenar oxigênio"
            },
            correctIndex = 3,
            questionNumber = 29,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/function_and_structure29",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_029",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Transportar oxigênio",
                "Manter estrutura das hemácias",
                "Contração dos pulmões",
                "Armazenar oxigênio"
            },
            correctIndex = 0,
            questionNumber = 30,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/function_and_structure30",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_030",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "Hemoglobina",
                "Mioglobina",
                "Não há diferença",
                "Ambas as proteínas tem baixa afinidade por oxigênio"
            },
            correctIndex = 1,
            questionNumber = 31,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/function_and_structure31",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_031",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "",
            answers = new string[] {
                "A mioglobina tem uma estrutura quaternária que facilita a ligação com O<sub><size=150%>2</size></sub>",
                "A hemoblogina pode assumir duas conformações, R e T, que têm diferentes afinidades por O<sub><size=150%>2</size></sub> ",
                "As proteínas não apresentam diferenças de afinidade por O<sub><size=150%>2</size></sub>",
                "Porque a hoglobina liga-se a quatro grupos heme"
            },
            correctIndex = 1,
            questionNumber = 32,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "AnswerImages/ProteinDB/function_and_structure32",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "proteins_032",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Unclassified,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As proteínas são polímeros formados por:",
            answers = new string[] {
                "Monossacarídeos",
                "Nucleotídeos",
                "Aminoácidos",
                "Lipídios"
            },
            correctIndex = 2,
            questionNumber = 34,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_034",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As proteínas são macromoléculas biológicas classificadas como polímeros, pois são formadas pela união encadeada de unidades menores chamadas aminoácidos, ligados entre si por ligações peptídicas. Existem 20 aminoácidos padrão que, combinados em diferentes sequências e quantidades, originam a enorme diversidade de proteínas encontradas nos seres vivos. Essa sequência de aminoácidos, determinada geneticamente, define a estrutura primária da proteína e, em última instância, todas as suas propriedades funcionais." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Qual é a ligação que une os aminoácidos em uma proteína?",
            answers = new string[] {
                "Ligação iônica",
                "Ligação de hidrogênio",
                "Ligação dissulfeto",
                "Ligação peptídica"
            },
            correctIndex = 3,
            questionNumber = 35,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_035",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A ligação peptídica é a ligação covalente que une os aminoácidos na cadeia polipeptídica de uma proteína. Ela é formada entre o grupo carboxila (-COOH) de um aminoácido e o grupo amino (-NH₂) do seguinte, com liberação de uma molécula de água — reação chamada de condensação. Embora outros tipos de ligação, como pontes de hidrogênio e pontes dissulfeto, participem da estabilização das estruturas superiores da proteína, é a ligação peptídica que constitui o elo covalente fundamental da cadeia principal." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A sequência linear de aminoácidos em uma proteína define sua:",
            answers = new string[] {
                "Estrutura primária",
                "Estrutura secundária",
                "Estrutura terciária",
                "Estrutura quaternária"
            },
            correctIndex = 0,
            questionNumber = 36,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_036",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura primária de uma proteína é simplesmente a sequência linear dos aminoácidos que a compõem, unidos por ligações peptídicas. Essa sequência é diretamente determinada pela informação genética e serve de base para todos os níveis superiores de organização estrutural: é ela que determina como a cadeia se dobrará, que interações serão formadas e, consequentemente, qual será a função da proteína. Alterações na estrutura primária — como mutações pontuais — podem modificar profundamente a função proteica, como ocorre na anemia falciforme." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As estruturas secundárias mais comuns das proteínas são:",
            answers = new string[] {
                "Hélice alfa e folha beta",
                "Dobra gama e alfa-barril",
                "Hélice dupla e tríplice folha",
                "Folha zeta e hélice delta"
            },
            correctIndex = 0,
            questionNumber = 37,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_037",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura secundária refere-se aos padrões regulares de dobramento local da cadeia polipeptídica, estabilizados por pontes de hidrogênio entre os grupos da cadeia principal. Os dois elementos mais comuns são a hélice alfa, em que a cadeia se enrola em espiral formando pontes de hidrogênio intracadeia a cada quatro resíduos, e a folha beta, em que segmentos estendidos da cadeia se alinham lado a lado formando uma estrutura pregueada. Ambas são blocos estruturais fundamentais presentes na grande maioria das proteínas conhecidas." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A estrutura terciária de uma proteína está relacionada à:",
            answers = new string[] {
                "Sequência de nucleotídeos",
                "Dobra tridimensional da cadeia polipeptídica",
                "Associação de várias subunidades",
                "Formação de pontes de hidrogênio apenas"
            },
            correctIndex = 1,
            questionNumber = 38,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_038",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura terciária corresponde ao arranjo tridimensional completo de uma única cadeia polipeptídica no espaço, resultante do dobramento de todos os seus elementos de estrutura secundária. Esse dobramento é estabilizado por interações entre as cadeias laterais dos aminoácidos, incluindo pontes de hidrogênio, interações hidrofóbicas, interações iônicas e pontes dissulfeto. É a estrutura terciária que define a forma final da proteína e, portanto, sua capacidade de interagir com outras moléculas e exercer sua função biológica específica." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Quando várias cadeias polipeptídicas se associam para formar uma proteína funcional, isso corresponde à:",
            answers = new string[] {
                "Estrutura primária",
                "Estrutura secundária",
                "Estrutura terciária",
                "Estrutura quaternária"
            },
            correctIndex = 3,
            questionNumber = 39,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_039",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura quaternária é o nível de organização proteica que envolve a associação não covalente de duas ou mais cadeias polipeptídicas (subunidades) em um único complexo funcional. Nem todas as proteínas possuem esse nível estrutural — apenas aquelas compostas por múltiplas subunidades. Um exemplo clássico é a hemoglobina, formada por quatro subunidades (dois pares de cadeias alfa e beta), cuja cooperatividade estrutural é essencial para a eficiência no transporte de oxigênio." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Qual das funções abaixo não é típica das proteínas?",
            answers = new string[] {
                "Catálise de reações (enzimas)",
                "Transporte de substâncias",
                "Defesa imunológica",
                "Armazenamento de informação genética"
            },
            correctIndex = 3,
            questionNumber = 40,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_040",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As proteínas desempenham funções extremamente diversas nos organismos vivos: atuam como catalisadores (enzimas), transportadores de substâncias (como a hemoglobina, que transporta oxigênio), anticorpos na defesa imunológica, hormônios, componentes estruturais (como o colágeno) e receptores de sinalização, entre muitas outras. O armazenamento de informação genética, no entanto, é uma função exclusiva dos ácidos nucleicos — DNA e RNA —, que codificam e transmitem as instruções para a síntese das próprias proteínas." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A hemoglobina é um exemplo de proteína que exerce função de:",
            answers = new string[] {
                "Reserva energética",
                "Transporte de oxigênio",
                "Defesa contra patógenos",
                "Catalisar reações"
            },
            correctIndex = 1,
            questionNumber = 41,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_041",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A hemoglobina é uma proteína globular presente nos eritrócitos (glóbulos vermelhos) cuja função principal é transportar oxigênio dos pulmões para os tecidos e auxiliar no retorno do dióxido de carbono dos tecidos para os pulmões. Ela possui estrutura quaternária, sendo formada por quatro subunidades polipeptídicas, cada uma contendo um grupo heme com um átomo de ferro que se liga reversivelmente ao oxigênio. A cooperatividade entre as subunidades torna a hemoglobina altamente eficiente na captação e liberação de oxigênio conforme as necessidades metabólicas dos tecidos." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "O processo em que uma proteína perde sua forma funcional devido a alterações de temperatura ou pH chama-se:",
            answers = new string[] {
                "Desnaturação",
                "Oxidação",
                "Polimerização",
                "Transcrição"
            },
            correctIndex = 0,
            questionNumber = 42,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_042",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A desnaturação é o processo pelo qual uma proteína perde sua estrutura tridimensional funcional devido à ação de agentes físicos ou químicos, como calor excessivo, variações extremas de pH, solventes orgânicos ou detergentes. Esses agentes rompem as interações não covalentes — pontes de hidrogênio, interações hidrofóbicas e iônicas — que mantêm o dobramento da proteína, sem necessariamente quebrar as ligações peptídicas da estrutura primária. Como a função proteica depende diretamente de sua conformação espacial, a desnaturação resulta em perda de atividade biológica, geralmente de forma irreversível." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As enzimas, que são catalisadores biológicos, são classificadas quimicamente como:",
            answers = new string[] {
                "Proteínas",
                "Lipídios",
                "Polissacarídeos",
                "Ácidos nucleicos"
            },
            correctIndex = 0,
            questionNumber = 43,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_043",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A grande maioria das enzimas são proteínas, classificadas quimicamente como polipeptídeos — cadeias de aminoácidos dobradas em estruturas tridimensionais precisas que formam o sítio ativo catalítico. Essa natureza proteica foi definitivamente comprovada em 1926, quando James Sumner cristalizou a urease e demonstrou que o cristal era composto por proteína. Vale mencionar que existem exceções: os ribozimas são moléculas de RNA com atividade catalítica, mostrando que nem todo catalisador biológico é necessariamente uma proteína, embora esses casos sejam minoritários." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As proteínas são polímeros formados por unidades chamadas:",
            answers = new string[] {
                "Monossacarídeos",
                "Nucleotídeos",
                "Aminoácidos",
                "Aminoácidos"
            },
            correctIndex = 2,
            questionNumber = 44,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_044",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As proteínas são polímeros biológicos cujas unidades estruturais básicas são os aminoácidos, moléculas que compartilham um núcleo comum — composto por um átomo de carbono central ligado a um grupo amino, um grupo carboxila e um átomo de hidrogênio — e diferem entre si pela cadeia lateral (grupo R), que confere a cada aminoácido suas propriedades físico-químicas únicas. Existem 20 aminoácidos padrão, e a variedade de sequências possíveis entre eles é o que gera a enorme diversidade estrutural e funcional das proteínas." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A ligação que une os aminoácidos em uma proteína é chamada:",
            answers = new string[] {
                "Glicosídica",
                "Peptídica",
                "Fosfodiéster",
                "Iônica"
            },
            correctIndex = 1,
            questionNumber = 45,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_045",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A ligação peptídica é a ligação covalente formada entre o grupo carboxila (-COOH) de um aminoácido e o grupo amino (-NH₂) do aminoácido seguinte, com liberação de uma molécula de água. Essa ligação é planar e possui caráter parcialmente duplo, o que restringe a rotação ao redor dela e influencia o dobramento da cadeia polipeptídica. As outras ligações mencionadas têm papéis distintos: as glicosídicas unem monossacarídeos, as fosfodiéster unem nucleotídeos nos ácidos nucleicos, e as iônicas participam da estabilização de estruturas proteicas superiores." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Qual estrutura da proteína corresponde à sequência linear de aminoácidos?",
            answers = new string[] {
                "Estrutura primária",
                "Estrutura secundária",
                "Estrutura terciária",
                "Estrutura quaternária"
            },
            correctIndex = 0,
            questionNumber = 46,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_046",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura primária é o primeiro e mais fundamental nível de organização proteica, correspondendo à sequência exata de aminoácidos ao longo da cadeia polipeptídica, unidos por ligações peptídicas. Essa sequência é determinada diretamente pelo código genético e serve de ponto de partida para todos os níveis estruturais superiores: é ela que vai ditar o dobramento espontâneo da proteína em sua forma tridimensional funcional. Qualquer alteração na estrutura primária — mesmo a substituição de um único aminoácido — pode ter consequências significativas sobre a função da proteína." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As hélices alfa e folhas beta são exemplos de qual nível de organização proteica?",
            answers = new string[] {
                "Primário",
                "Secundário",
                "Terciário",
                "Quaternário"
            },
            correctIndex = 1,
            questionNumber = 47,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_047",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A hélice alfa e a folha beta são os dois principais elementos de estrutura secundária das proteínas, ou seja, padrões regulares de dobramento local da cadeia polipeptídica estabilizados por pontes de hidrogênio entre os grupos da cadeia principal. Na hélice alfa, as pontes de hidrogênio ocorrem dentro da própria cadeia, formando uma espiral compacta; nas folhas beta, segmentos adjacentes da cadeia se alinham lado a lado. Esses elementos são os blocos construtivos que, combinados e empacotados, darão origem à estrutura tridimensional completa da proteína." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A hemoglobina é exemplo de proteína com estrutura:",
            answers = new string[] {
                "Primário",
                "Secundário",
                "Terciário",
                "Quaternário"
            },
            correctIndex = 3,
            questionNumber = 48,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_048",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A hemoglobina é o exemplo mais clássico de proteína com estrutura quaternária, sendo formada pela associação de quatro subunidades polipeptídicas: duas cadeias alfa e duas cadeias beta, cada uma contendo um grupo heme com ferro responsável pela ligação ao oxigênio. A estrutura quaternária não é apenas um detalhe organizacional — ela é essencial para a função da hemoglobina, pois a cooperatividade entre as subunidades permite que a proteína capte oxigênio nos pulmões e o libere eficientemente nos tecidos periféricos, conforme a demanda metabólica local." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Qual é a função principal das enzimas, que são proteínas especializadas?",
            answers = new string[] {
                "Armazenar energia",
                "Catalisar reações químicas",
                "Transportar gases",
                "Formar membranas"
            },
            correctIndex = 1,
            questionNumber = 49,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_049",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As enzimas são proteínas especializadas que atuam como catalisadores biológicos, ou seja, aceleram as reações químicas do metabolismo celular sem serem consumidas no processo. Elas fazem isso reduzindo a energia de ativação necessária para que a reação ocorra, estabilizando o estado de transição entre reagentes e produtos. Cada enzima é altamente específica, reconhecendo apenas determinados substratos e catalisando um tipo particular de transformação química, o que permite à célula regular suas vias metabólicas com grande precisão e eficiência." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "O colágeno, proteína encontrada em tecidos conjuntivos, tem função principalmente:",
            answers = new string[] {
                "Energética",
                "Estrutural",
                "Catalítica",
                "Hormonal"
            },
            correctIndex = 1,
            questionNumber = 50,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_050",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "O colágeno é a proteína mais abundante do corpo humano e exerce função predominantemente estrutural, conferindo resistência mecânica e elasticidade aos tecidos conjuntivos, como pele, tendões, ligamentos, cartilagens e ossos. Sua estrutura característica é uma tripla hélice formada por três cadeias polipeptídicas enroladas entre si, rica em glicina, prolina e hidroxiprolina. Essa organização confere ao colágeno grande resistência à tração, tornando-o um componente essencial da matriz extracelular que sustenta e integra os tecidos do organismo." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A desnaturação de uma proteína pode ser causada por:",
            answers = new string[] {
                "Aumento de temperatura ou variação extrema de pH",
                "Formação de ligação peptídica",
                "Diminuição da concentração de glicose",
                "Ação de oxigênio atmosférico"
            },
            correctIndex = 0,
            questionNumber = 51,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_051",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A desnaturação proteica ocorre quando agentes físicos ou químicos rompem as interações não covalentes — pontes de hidrogênio, interações hidrofóbicas e iônicas — que mantêm o dobramento tridimensional da proteína. O calor excessivo aumenta a agitação molecular a ponto de desfazer essas interações, enquanto variações extremas de pH alteram o estado de ionização dos aminoácidos, desestabilizando a estrutura. Solventes orgânicos e detergentes também podem causar desnaturação. Em geral, a estrutura primária (sequência de aminoácidos) permanece intacta, mas a função biológica é perdida." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A insulina é um exemplo de proteína com função:",
            answers = new string[] {
                "Hormonal",
                "Estrutural",
                "Energética",
                "Enzimática"
            },
            correctIndex = 0,
            questionNumber = 52,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_052",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A insulina é um hormônio peptídico produzido pelas células beta do pâncreas e secretado em resposta ao aumento da glicemia após uma refeição. Sua função reguladora é fundamental: ela sinaliza para as células do organismo — especialmente do fígado, músculo e tecido adiposo — que capturem a glicose circulante, reduzindo os níveis sanguíneos de açúcar. A insulina é composta por duas cadeias polipeptídicas unidas por pontes dissulfeto e é um exemplo clássico de proteína com função hormonal, atuando como mensageiro químico no controle do metabolismo de carboidratos." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As proteínas podem atuar no transporte de moléculas. Um exemplo é:",
            answers = new string[] {
                "DNA",
                "Hemoglobina",
                "Glicogênio",
                "Amido"
            },
            correctIndex = 1,
            questionNumber = 53,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_053",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A hemoglobina é o exemplo mais clássico de proteína transportadora, sendo responsável por carregar oxigênio dos pulmões para os tecidos e participar do transporte de dióxido de carbono no sentido contrário. Ela é composta por quatro subunidades polipeptídicas, cada uma com um grupo heme contendo ferro, que se liga reversivelmente ao oxigênio. Além da hemoglobina, outras proteínas transportadoras incluem a mioglobina (transporta oxigênio no músculo), a albumina sérica (transporta ácidos graxos e outras moléculas no sangue) e as proteínas de membrana que formam canais e transportadores iônicos." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A ligação que une os aminoácidos na formação das proteínas é chamada de:",
            answers = new string[] {
                "Ligação de hidrogênio",
                "Ligação glicosídica",
                "Ligação peptídica",
                "Ligação fosfodiéster"
            },
            correctIndex = 2,
            questionNumber = 54,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_054",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A ligação peptídica é a ligação covalente que une os aminoácidos em uma cadeia polipeptídica, formando-se entre o grupo carboxila (-COOH) de um aminoácido e o grupo amino (-NH₂) do seguinte, com liberação de uma molécula de água. Essa ligação possui caráter parcialmente duplo, conferindo rigidez planar à região da cadeia principal onde ocorre. As demais ligações mencionadas têm papéis distintos: a glicosídica une monossacarídeos, a fosfodiéster conecta nucleotídeos nos ácidos nucleicos, e as de hidrogênio estabilizam estruturas secundárias e terciárias das proteínas." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A estrutura tridimensional que representa o dobramento total da proteína é a:",
            answers = new string[] {
                "Estrutura primária",
                "Estrutura secundária",
                "Estrutura terciária",
                "Estrutura quaternária"
            },
            correctIndex = 2,
            questionNumber = 55,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_055",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura terciária corresponde ao dobramento tridimensional completo de uma única cadeia polipeptídica, resultante da combinação e empacotamento de todos os seus elementos de estrutura secundária no espaço. Esse dobramento é estabilizado por interações entre as cadeias laterais dos aminoácidos — pontes de hidrogênio, interações hidrofóbicas, interações iônicas e pontes dissulfeto — e define a forma globular ou fibrosa final da proteína. É nesse nível estrutural que o sítio ativo das enzimas e os sítios de ligação de outras proteínas são formados, tornando a estrutura terciária essencial para a função biológica." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A sequência linear de aminoácidos em uma proteína corresponde à:",
            answers = new string[] {
                "Estrutura primária",
                "Estrutura secundária",
                "Estrutura terciária",
                "Estrutura quaternária"
            },
            correctIndex = 0,
            questionNumber = 56,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_056",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura primária é o nível mais fundamental de organização proteica e corresponde à sequência exata dos aminoácidos ao longo da cadeia polipeptídica, determinada diretamente pelo código genético. Ela é o ponto de partida para todos os níveis estruturais superiores: a sequência de aminoácidos dita quais interações serão possíveis e, portanto, como a proteína se dobrará espontaneamente em sua conformação tridimensional funcional. Alterações na estrutura primária, mesmo mínimas, podem comprometer drasticamente a função proteica — como demonstrado pela anemia falciforme, causada pela substituição de um único aminoácido na hemoglobina." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A hemoglobina é um exemplo de proteína com:",
            answers = new string[] {
                "Estrutura primária",
                "Estrutura secundária",
                "Estrutura terciária",
                "Estrutura quaternária"
            },
            correctIndex = 3,
            questionNumber = 57,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_057",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A hemoglobina é o exemplo mais citado de proteína com estrutura quaternária, sendo formada pela associação de quatro subunidades polipeptídicas — duas cadeias alfa e duas cadeias beta — mantidas juntas por interações não covalentes. Cada subunidade contém um grupo heme com ferro, responsável pela ligação reversa ao oxigênio. A estrutura quaternária não é apenas organizacional: a cooperatividade entre as quatro subunidades é o que torna a hemoglobina tão eficiente, permitindo que ela capte oxigênio nos pulmões com alta afinidade e o libere nos tecidos periféricos onde a demanda é maior." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As proteínas podem atuar como:",
            answers = new string[] {
                "Catalisadores biológicos, hormônios e elementos estruturais",
                "Fonte primária de energia imediata, como a glicose",
                "Material genético das células",
                "Lipídios armazenados em vacúolos"
            },
            correctIndex = 0,
            questionNumber = 58,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_058",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As proteínas são as biomoléculas de maior versatilidade funcional nos organismos vivos, atuando em praticamente todos os processos biológicos. Como catalisadores biológicos, as enzimas aceleram reações metabólicas; como hormônios, como a insulina, regulam processos fisiológicos; como elementos estruturais, o colágeno e a queratina conferem resistência e forma aos tecidos. Além dessas funções, proteínas também atuam no transporte de moléculas, na defesa imunológica (anticorpos), na contração muscular (actina e miosina) e na sinalização celular, entre muitas outras." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A desnaturação de uma proteína ocorre quando:",
            answers = new string[] {
                "Ela perde sua sequência primária",
                "Suas interações químicas são rompidas, alterando sua forma",
                "Há aumento da quantidade de aminoácidos",
                "Ela se torna insolúvel em lipídeos"
            },
            correctIndex = 1,
            questionNumber = 59,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_059",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A desnaturação de uma proteína ocorre quando as interações não covalentes que sustentam sua estrutura tridimensional — como pontes de hidrogênio, interações hidrofóbicas e interações iônicas — são rompidas por agentes físicos ou químicos. Com o desdobramento da cadeia polipeptídica, o sítio ativo ou outros domínios funcionais são desfeitos, e a proteína perde sua atividade biológica. É importante destacar que a desnaturação não quebra as ligações peptídicas da estrutura primária: a sequência de aminoácidos permanece intacta, mas a forma funcional é perdida." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A desnaturação de uma proteína ocorre quando:",
            answers = new string[] {
                "Ela perde sua sequência primária",
                "Suas interações químicas são rompidas, alterando sua forma",
                "Há aumento da quantidade de aminoácidos",
                "Ela se torna insolúvel em lipídeos"
            },
            correctIndex = 1,
            questionNumber = 60,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_060",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A desnaturação de uma proteína ocorre quando as interações não covalentes que sustentam sua estrutura tridimensional — como pontes de hidrogênio, interações hidrofóbicas e interações iônicas — são rompidas por agentes físicos ou químicos. Com o desdobramento da cadeia polipeptídica, o sítio ativo ou outros domínios funcionais são desfeitos, e a proteína perde sua atividade biológica. É importante destacar que a desnaturação não quebra as ligações peptídicas da estrutura primária: a sequência de aminoácidos permanece intacta, mas a forma funcional é perdida." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Qual dessas proteínas atua no transporte de oxigênio no sangue?",
            answers = new string[] {
                "Insulina",
                "Hemoglobina",
                "Colágeno",
                "Tripsina"
            },
            correctIndex = 1,
            questionNumber = 61,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_061",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A hemoglobina é a proteína presente nos eritrócitos (glóbulos vermelhos) responsável pelo transporte de oxigênio no sangue. Cada molécula de hemoglobina é formada por quatro subunidades polipeptídicas, cada uma contendo um grupo heme com ferro que se liga reversivelmente ao oxigênio nos pulmões e o libera nos tecidos periféricos. As demais proteínas mencionadas têm funções distintas: a insulina é um hormônio regulador da glicemia, o colágeno é uma proteína estrutural dos tecidos conjuntivos, e a tripsina é uma protease digestiva pancreática." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A estrutura primária de uma proteína refere-se a:",
            answers = new string[] {
                "O enovelamento tridimensional da proteína",
                "A sequência linear de aminoácidos",
                "A associação de várias cadeias polipeptídicas",
                "A formação de hélices alfa e folhas beta"
            },
            correctIndex = 1,
            questionNumber = 62,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_062",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A estrutura primária é o nível mais básico de organização de uma proteína e consiste na sequência linear e específica dos aminoácidos que compõem a cadeia polipeptídica, unidos por ligações peptídicas. Essa sequência é determinada diretamente pela informação genética e é única para cada proteína. Ela serve de base para todos os níveis estruturais superiores, pois são as propriedades físico-químicas das cadeias laterais dos aminoácidos — definidas pela estrutura primária — que ditarão o dobramento espontâneo da proteína em sua conformação funcional." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A insulina é um exemplo de proteína com função:",
            answers = new string[] {
                "Estrutural",
                "Hormonal",
                "Catalítica",
                "Energética"
            },
            correctIndex = 1,
            questionNumber = 63,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_063",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A insulina é um hormônio peptídico produzido pelas células beta das ilhotas de Langerhans do pâncreas, sendo secretada em resposta ao aumento dos níveis de glicose no sangue após uma refeição. Sua função é essencialmente reguladora: ela promove a captação de glicose pelas células dos tecidos-alvo, estimula a síntese de glicogênio no fígado e músculo, e inibe a degradação de gorduras. A insulina é composta por duas cadeias polipeptídicas unidas por pontes dissulfeto e é um dos exemplos mais estudados de proteína com função hormonal no metabolismo humano." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A insulina é um exemplo de proteína com função:",
            answers = new string[] {
                "Estrutural",
                "Hormonal",
                "Catalítica",
                "Energética"
            },
            correctIndex = 1,
            questionNumber = 64,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_064",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A insulina é um hormônio peptídico produzido pelas células beta das ilhotas de Langerhans do pâncreas, sendo secretada em resposta ao aumento dos níveis de glicose no sangue após uma refeição. Sua função é essencialmente reguladora: ela promove a captação de glicose pelas células dos tecidos-alvo, estimula a síntese de glicogênio no fígado e músculo, e inibe a degradação de gorduras. A insulina é composta por duas cadeias polipeptídicas unidas por pontes dissulfeto e é um dos exemplos mais estudados de proteína com função hormonal no metabolismo humano." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As proteínas podem atuar como:",
            answers = new string[] {
                "Catalisadores biológicos (enzimas)",
                "Moléculas de armazenamento de energia imediata",
                "Componentes principais da membrana nuclear",
                "Moléculas de informação genética"
            },
            correctIndex = 0,
            questionNumber = 65,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_065",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As proteínas são as biomoléculas funcionalmente mais versáteis nos organismos vivos. Uma de suas funções mais importantes é a catálise biológica: as enzimas são proteínas que aceleram as reações químicas do metabolismo ao reduzir a energia de ativação necessária, tornando viáveis transformações que de outra forma seriam extremamente lentas. Além de catalisadoras, proteínas também atuam como hormônios reguladores, transportadoras de moléculas, anticorpos de defesa imunológica, componentes estruturais dos tecidos e receptores de sinalização celular." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Qual desses fatores pode desnaturar uma proteína?",
            answers = new string[] {
                "Temperatura elevada",
                "pH extremo",
                "Presença de solventes orgânicos",
                "Todas as anteriores"
            },
            correctIndex = 3,
            questionNumber = 66,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_066",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Diversos agentes são capazes de desnaturar proteínas ao romper as interações não covalentes que mantêm sua estrutura tridimensional. Temperatura elevada aumenta a agitação molecular e desfaz pontes de hidrogênio e interações hidrofóbicas; pH extremo altera o estado de ionização dos aminoácidos, perturbando as interações iônicas e conformação da cadeia; e solventes orgânicos competem pelas interações hidrofóbicas que mantêm o núcleo proteico compacto. Em todos os casos, o resultado é o desdobramento da proteína e a perda de sua função biológica, geralmente de forma irreversível." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Qual desses fatores pode desnaturar uma proteína?",
            answers = new string[] {
                "Temperatura elevada",
                "pH extremo",
                "Presença de solventes orgânicos",
                "Todas as anteriores"
            },
            correctIndex = 3,
            questionNumber = 67,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_067",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Diversos agentes são capazes de desnaturar proteínas ao romper as interações não covalentes que mantêm sua estrutura tridimensional. Temperatura elevada aumenta a agitação molecular e desfaz pontes de hidrogênio e interações hidrofóbicas; pH extremo altera o estado de ionização dos aminoácidos, perturbando as interações iônicas e conformação da cadeia; e solventes orgânicos competem pelas interações hidrofóbicas que mantêm o núcleo proteico compacto. Em todos os casos, o resultado é o desdobramento da proteína e a perda de sua função biológica, geralmente de forma irreversível." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "A albumina presente no ovo é uma proteína com função principalmente:",
            answers = new string[] {
                "Hormonal",
                "Energética e de reserva",
                "Estrutural",
                "Transportadora de oxigênio"
            },
            correctIndex = 1,
            questionNumber = 68,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_068",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "A albumina presente na clara do ovo (ovalbumina) é uma proteína com função predominantemente de reserva nutricional, fornecendo aminoácidos essenciais para o desenvolvimento do embrião durante a incubação. É uma das proteínas mais estudadas na história da bioquímica e se torna um exemplo cotidiano de desnaturação quando o ovo é cozido: o calor rompe as interações que mantêm sua estrutura tridimensional, fazendo a clara solidificar e mudar de transparente para branca — processo irreversível que ilustra visivelmente a desnaturação proteica." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As proteínas chamadas fibrosas, como a queratina e o colágeno, têm função principal:",
            answers = new string[] {
                "Hormonal",
                "Catalítica",
                "Estrutural",
                "De defesa imunológica"
            },
            correctIndex = 2,
            questionNumber = 69,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_069",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "As proteínas fibrosas são caracterizadas por cadeias polipeptídicas alongadas e organizadas em estruturas repetitivas e resistentes, em contraste com as proteínas globulares de forma compacta. Sua função é predominantemente estrutural: a queratina forma cabelos, unhas, penas e chifres, conferindo proteção e resistência mecânica; o colágeno sustenta pele, tendões, ossos e cartilagens; e a elastina confere elasticidade a tecidos como vasos sanguíneos e pulmões. Essas proteínas são insolúveis em água e extremamente estáveis, características ideais para seu papel de suporte e proteção nos organismos." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "Os anticorpos (imunoglobulinas) são proteínas com função:",
            answers = new string[] {
                "Energética",
                "Estrutural",
                "De defesa",
                "Hormonal"
            },
            correctIndex = 2,
            questionNumber = 70,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_070",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Os anticorpos, ou imunoglobulinas, são proteínas produzidas pelos linfócitos B do sistema imunológico em resposta à presença de antígenos — moléculas estranhas ao organismo, como as presentes em vírus, bactérias e toxinas. Cada anticorpo possui uma região variável altamente específica que reconhece e se liga ao antígeno correspondente, neutralizando-o ou marcando-o para destruição por outras células do sistema imune. As imunoglobulinas são proteínas globulares com estrutura quaternária, formadas por duas cadeias pesadas e duas cadeias leves unidas por pontes dissulfeto, e são o principal componente da imunidade humoral." }
        },
        new Question
        {
            questionDatabankName = "ProteinQuestionDatabase",
            questionText = "As proteínas que atuam como hormônios, como a insulina, têm função:",
            answers = new string[] {
                "Estrutural",
                "Reguladora",
                "Energética",
                "De transporte"
            },
            correctIndex = 1,
            questionNumber = 71,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "proteins_071",
            topic = "proteins",
            subtopic = null,
            displayName = "Proteínas",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = new QuestionHint { text = "Proteínas com função hormonal atuam como mensageiros químicos que regulam processos fisiológicos em células e tecidos distantes do local onde foram produzidas. A insulina, produzida pelo pâncreas, regula os níveis de glicose no sangue; o glucagon, também pancreático, age de forma oposta; e o hormônio do crescimento (GH), produzido pela hipófise, regula o crescimento e o metabolismo. Esses hormônios proteicos geralmente se ligam a receptores específicos na superfície das células-alvo, desencadeando cascatas de sinalização intracelular que modificam o comportamento celular de acordo com as necessidades do organismo." }
        }
    };

    public List<Question> GetQuestions() => questions;
    public QuestionSet GetQuestionSetType() => QuestionSet.proteins;
    public string GetDatabankName()  => "ProteinQuestionDatabase";
    public string GetDisplayName()   => "Proteínas";
    public bool IsDatabaseInDevelopment() => databaseInDevelopment;
}
