using System.Collections.Generic;
using QuestionSystem;

public class WaterQuestionDatabase : IQuestionDatabase
{
    private bool databaseInDevelopment = false;

    private List<Question> questions = new List<Question>
    {
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual a principal razão para a alta capacidade calorífica da água?",
            answers = new string[] {
                "Fortes ligações covalentes entre átomos de hidrogênio e oxigênio.",
                "Intensas ligações de hidrogênio entre moléculas de água.",
                "Alto peso molecular das moléculas de água.",
                "Seu estado líquido em temperatura ambiente."
            },
            correctIndex = 1,
            questionNumber = 1,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_001",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual das propriedades da água é MAIS responsável por sua capacidade de moderar a temperatura?",
            answers = new string[] {
                "Alto calor de vaporização",
                "Alta tensão superficial",
                "Alto calor específico",
                "Alta densidade"
            },
            correctIndex = 2,
            questionNumber = 2,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_002",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Por que o gelo flutua na água?",
            answers = new string[] {
                "O gelo é menos denso que a água líquida.",
                "O gelo possui maior tensão superficial que a água líquida.",
                "O gelo possui menor calor específico que a água líquida.",
                "O gelo é uma substância diferente da água."
            },
            correctIndex = 0,
            questionNumber = 3,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_003",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual propriedade da água permite que insetos caminhem na superfície?",
            answers = new string[] {
                "Alto calor específico",
                "Alto calor de vaporização",
                "Alta tensão superficial",
                "Baixa densidade"
            },
            correctIndex = 2,
            questionNumber = 4,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_004",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText= "Suar ajuda a esfriar o corpo principalmente devido ao:",
            answers = new string[] {
                "Alto calor específico da água",
                "Alta densidade da água",
                "Alto calor de vaporização da água",
                "Baixa viscosidade da água"
            },
            correctIndex = 2,
            questionNumber = 5,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_005",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O alto calor de vaporização da água se deve principalmente a:",
            answers = new string[] {
                "Fortes ligações covalentes",
                "Intensas ligações de hidrogênio",
                "Alta tensão superficial",
                "Baixa viscosidade"
            },
            correctIndex = 1,
            questionNumber = 6,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_006",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual substância requer mais energia para elevar sua temperatura em 1°C?",
            answers = new string[] {
                "Álcool",
                "Água",
                "Clorofórmio",
                "Todas requerem a mesma quantidade de energia"
            },
            correctIndex = 1,
            questionNumber = 7,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_007",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Uma substância com alto calor de vaporização irá:",
            answers = new string[] {
                "Resfriar rapidamente ao evaporar",
                "Aquecer rapidamente ao evaporar",
                "Manter temperatura constante durante a evaporação",
                "Não evaporar facilmente"
            },
            correctIndex = 0,
            questionNumber = 8,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_008",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Por que a água é um excelente solvente para muitos compostos iônicos?",
            answers = new string[] {
                "Alta tensão superficial",
                "Alta polaridade e formação de ligações de hidrogênio",
                "Baixa viscosidade",
                "Alta capacidade calorífica"
            },
            correctIndex = 1,
            questionNumber = 9,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_009",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O que causa a alta tensão superficial da água?",
            answers = new string[] {
                "Ligações covalentes entre H e O",
                "Ligações de hidrogênio entre moléculas de água",
                "Interações iônicas entre moléculas de água",
                "Forças de Van der Waals"
            },
            correctIndex = 1,
            questionNumber = 10,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_010",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A polaridade da molécula de água se deve a:",
            answers = new string[] {
                "Compartilhamento igual de elétrons",
                "Compartilhamento desigual de elétrons",
                "Presença de ligações de hidrogênio",
                "Alto peso molecular"
            },
            correctIndex = 1,
            questionNumber = 11,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_011",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A água é uma molécula polar porque:",
            answers = new string[] {
                "Forma simétrica",
                "Extremidades levemente positivas e negativas",
                "É líquida em temperatura ambiente",
                "Dissolve facilmente substâncias apolares"
            },
            correctIndex = 1,
            questionNumber = 12,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_012",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O que NÃO é consequência das ligações de hidrogênio na água?",
            answers = new string[] {
                "Alta tensão superficial",
                "Alto ponto de ebulição",
                "Alta pressão de vapor",
                "Gelo menos denso que água líquida"
            },
            correctIndex = 2,
            questionNumber = 13,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_013",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Que tipo de ligação causa a coesão entre moléculas de água?",
            answers = new string[] {
                "Iônicas",
                "Covalentes",
                "Hidrogênio",
                "Van der Waals"
            },
            correctIndex = 2,
            questionNumber = 14,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_014",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Ligações de hidrogênio se formam entre:",
            answers = new string[] {
                "Dois átomos de hidrogênio",
                "Hidrogênio e oxigênio",
                "Dois átomos de oxigênio",
                "Carbono e hidrogênio"
            },
            correctIndex = 1,
            questionNumber = 15,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_015",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Um estudante compara as ligações covalentes O-H dentro da molécula de água com as ligações de hidrogênio entre moléculas de água. Qual análise está correta?",
            answers = new string[] {
                "As duas ligações têm a mesma força e a mesma função estrutural.",
                "As covalentes são intramoleculares e mais fortes; as de hidrogênio são intermoleculares e explicam propriedades coletivas da água.",
                "As ligações de hidrogênio mantêm os átomos H e O unidos dentro da molécula de água.",
                "As ligações covalentes só aparecem quando a água congela."
            },
            correctIndex = 1,
            questionNumber = 16,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_016",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Ao observar uma molécula de água com geometria angular, qual previsão sobre sua polaridade é mais adequada?",
            answers = new string[] {
                "A molécula será apolar porque os dipolos se anulam completamente.",
                "A molécula será polar porque a geometria angular mantém um dipolo resultante.",
                "A molécula será iônica porque possui hidrogênio e oxigênio.",
                "A molécula não terá regiões parcialmente carregadas."
            },
            correctIndex = 1,
            questionNumber = 17,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/water_bent_polarity",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_017",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Em uma solução aquosa, um íon Na<sup><size=150%>+</size></sup> tenderia a se aproximar de qual região da molécula de água?",
            answers = new string[] {
                "Da região próxima ao oxigênio, parcialmente negativa.",
                "Da região próxima aos hidrogênios, parcialmente negativa.",
                "Do centro geométrico da molécula, sem carga parcial.",
                "De nenhuma região, pois íons não interagem com água."
            },
            correctIndex = 0,
            questionNumber = 18,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/water_polarity_ion_interaction",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_018",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Molécula com regiões polares e apolares é chamada de:",
            answers = new string[] {
                "Anfipática",
                "Hidrofílica",
                "Hidrofóbica",
                "Polar"
            },
            correctIndex = 0,
            questionNumber = 19,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_019",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual tipo de molécula se dissolve mais facilmente em água?",
            answers = new string[] {
                "Apolar",
                "Polar",
                "Grande",
                "Pequena"
            },
            correctIndex = 1,
            questionNumber = 20,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_020",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Substância que se dissolve em água é:",
            answers = new string[] {
                "Hidrofóbica",
                "Hidrofílica",
                "Anfipática",
                "Aquosa"
            },
            correctIndex = 1,
            questionNumber = 21,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_021",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Substância que NÃO se dissolve em água é:",
            answers = new string[] {
                "Hidrofílica",
                "Hidrofóbica",
                "Anfipática",
                "Aquosa"
            },
            correctIndex = 1,
            questionNumber = 22,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_022",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A dissolução de composto iônico em água se deve a:",
            answers = new string[] {
                "Ligações de hidrogênio",
                "Interações hidrofóbicas",
                "Interações íon-dipolo",
                "Forças de Van der Waals"
            },
            correctIndex = 2,
            questionNumber = 23,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_023",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A imagem mostra moléculas de água organizadas ao redor de um íon positivo. Qual análise explica melhor essa organização?",
            answers = new string[] {
                "Os oxigênios parcialmente negativos apontam para o cátion, formando uma camada de hidratação por interações íon-dipolo.",
                "Os hidrogênios parcialmente negativos apontam para o cátion, formando ligações covalentes.",
                "As moléculas de água se organizam como micelas porque o íon é hidrofóbico.",
                "A água não interage com íons; a organização é aleatória."
            },
            correctIndex = 0,
            questionNumber = 24,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/hydration_shell_cation",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_024",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Alta constante dielétrica indica capacidade de:",
            answers = new string[] {
                "Reduzir força entre íons opostos",
                "Aumentar força entre íons opostos",
                "Não afetar interações iônicas",
                "Dissolver apenas substâncias apolares"
            },
            correctIndex = 0,
            questionNumber = 25,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_025",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O que NÃO afeta a solubilidade de gases em água?",
            answers = new string[] {
                "Temperatura",
                "Pressão",
                "Polaridade do gás",
                "Peso molecular do solvente"
            },
            correctIndex = 3,
            questionNumber = 26,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_026",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A solubilidade de gases em água:",
            answers = new string[] {
                "Aumenta com temperatura",
                "Diminui com temperatura",
                "Não é afetada pela temperatura",
                "É afetada apenas pela pressão"
            },
            correctIndex = 1,
            questionNumber = 27,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_027",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Como detergentes removem gordura?",
            answers = new string[] {
                "Dissolvendo diretamente",
                "Formando micelas",
                "Reagindo quimicamente",
                "Aumentando tensão superficial"
            },
            correctIndex = 1,
            questionNumber = 28,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_028",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Moléculas anfipáticas com uma cauda hidrofóbica são colocadas em água. Qual estrutura melhor reduz o contato das caudas com a água?",
            answers = new string[] {
                "Camadas de hidratação em torno de íons.",
                "Micelas com caudas voltadas para o interior.",
                "Ligações de hidrogênio entre as caudas apolares.",
                "Moléculas isoladas, sem organização."
            },
            correctIndex = 1,
            questionNumber = 29,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/micelle_amphipathic",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_029",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Por que fosfolipídios, e não carboidratos ou ácidos nucleicos, formam a estrutura básica das membranas celulares?",
            answers = new string[] {
                "Porque possuem regiões hidrofílicas e hidrofóbicas que se organizam espontaneamente em bicamadas na água.",
                "Porque são completamente solúveis em água e se espalham como moléculas isoladas.",
                "Porque armazenam informação genética e por isso formam barreiras celulares.",
                "Porque são polímeros rígidos que impedem qualquer movimento lateral."
            },
            correctIndex = 0,
            questionNumber = 30,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/phospholipid_bilayer",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_030",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Por que membranas celulares são fluidas?",
            answers = new string[] {
                "Fosfolipídios compactados",
                "Fosfolipídios livres para se mover",
                "Proteínas fixas aos fosfolipídios",
                "Membrana impermeável à água"
            },
            correctIndex = 1,
            questionNumber = 31,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_031",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Caudas hidrofóbicas de fosfolipídios em membranas celulares ficam:",
            answers = new string[] {
                "Ambiente extracelular",
                "Ambiente intracelular",
                "Uma para a outra, no interior da membrana",
                "Ambientes extra e intracelular"
            },
            correctIndex = 2,
            questionNumber = 32,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_032",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual desses gases é MENOS solúvel em água?",
            answers = new string[] {
                "Oxigênio",
                "Dióxido de carbono",
                "Nitrogênio",
                "Amônia"
            },
            correctIndex = 2,
            questionNumber = 33,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_033",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Comparando N<sub><size=150%>2</size></sub>, O<sub><size=150%>2</size></sub>, CO<sub><size=150%>2</size></sub> e NH<sub><size=150%>3</size></sub>, qual análise explica por que gases mais polares tendem a ser mais solúveis em água?",
            answers = new string[] {
                "Gases polares interagem melhor com a água por dipolos ou ligações de hidrogênio, enquanto gases apolares interagem pouco.",
                "Gases apolares sempre formam mais ligações de hidrogênio que gases polares.",
                "A solubilidade depende apenas do tamanho da molécula, não das interações com água.",
                "Todos os gases têm a mesma solubilidade porque a água é solvente universal."
            },
            correctIndex = 0,
            questionNumber = 34,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_034",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Peixes obtêm oxigênio da água através de:",
            answers = new string[] {
                "Pele",
                "Brânquias",
                "Bebendo água",
                "Pulmões"
            },
            correctIndex = 1,
            questionNumber = 35,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_035",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Função principal das brânquias em peixes é:",
            answers = new string[] {
                "Filtrar alimento",
                "Regular temperatura",
                "Extrair oxigênio",
                "Controlar flutuabilidade"
            },
            correctIndex = 2,
            questionNumber = 36,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_036",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Uma amostra contém 10 moléculas de água. Quantos átomos de hidrogênio e oxigênio há nessa amostra?",
            answers = new string[] {
                "10 hidrogênios e 10 oxigênios",
                "20 hidrogênios e 10 oxigênios",
                "10 hidrogênios e 20 oxigênios",
                "20 hidrogênios e 20 oxigênios"
            },
            correctIndex = 1,
            questionNumber = 37,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/water_molecule_formula",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_037",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Usando massa molecular aproximada da água de 18 g/mol, qual é a massa de 2 mol de água?",
            answers = new string[] {
                "9 g",
                "18 g",
                "36 g",
                "54 g"
            },
            correctIndex = 2,
            questionNumber = 38,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_038",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Um cubo de gelo com densidade aproximada de 0,92 g/mL é colocado em água líquida a 4°C, com densidade de 1,00 g/mL. O que deve acontecer?",
            answers = new string[] {
                "O gelo afunda porque é sólido.",
                "O gelo flutua porque é menos denso que a água líquida.",
                "O gelo se dissolve imediatamente por ser apolar.",
                "O gelo fica suspenso porque tem a mesma densidade da água."
            },
            correctIndex = 1,
            questionNumber = 39,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_039",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Um estudante afirma: \"A água pura sempre ferve a 100°C\". Qual avaliação é mais correta?",
            answers = new string[] {
                "A afirmação é correta em qualquer condição, pois o ponto de ebulição é fixo.",
                "A afirmação é adequada ao nível do mar, mas deve considerar mudanças de pressão atmosférica.",
                "A afirmação é falsa porque água pura nunca ferve a 100°C.",
                "A afirmação só é correta quando a água contém sais."
            },
            correctIndex = 1,
            questionNumber = 40,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_040",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Uma solução aquosa com solutos não congela exatamente a 0°C. Qual explicação avalia melhor esse resultado?",
            answers = new string[] {
                "Solutos podem reduzir o ponto de congelamento, então 0°C vale como referência para água pura.",
                "A água nunca congela a 0°C, mesmo quando pura.",
                "A presença de solutos elimina as ligações covalentes da água.",
                "A solução passa a ser apolar e por isso não congela."
            },
            correctIndex = 0,
            questionNumber = 41,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_041",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A afirmação \"água pura sempre tem pH 7\" deve ser avaliada como:",
            answers = new string[] {
                "Sempre correta, pois o pH da água pura nunca muda.",
                "Adequada como referência a 25°C, mas incompleta porque o pH neutro varia com a temperatura.",
                "Sempre falsa, pois água pura é naturalmente ácida.",
                "Correta apenas se houver sais dissolvidos."
            },
            correctIndex = 1,
            questionNumber = 42,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_042",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Água pura é:",
            answers = new string[] {
                "Ácida",
                "Básica",
                "Neutra",
                "Depende da temperatura"
            },
            correctIndex = 2,
            questionNumber = 43,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_043",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual ligação é mais forte?",
            answers = new string[] {
                "Hidrogênio",
                "Covalente",
                "Força igual",
                "Depende dos átomos"
            },
            correctIndex = 1,
            questionNumber = 44,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_044",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Atração entre moléculas de água:",
            answers = new string[] {
                "Coesão",
                "Adesão",
                "Tensão superficial",
                "Ação capilar"
            },
            correctIndex = 0,
            questionNumber = 45,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_045",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Atração entre água e outras substâncias polares:",
            answers = new string[] {
                "Coesão",
                "Adesão",
                "Tensão superficial",
                "Ação capilar"
            },
            correctIndex = 1,
            questionNumber = 46,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_046",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Movimento da água contra a gravidade em plantas:",
            answers = new string[] {
                "Osmose",
                "Difusão",
                "Transpiração",
                "Ação capilar"
            },
            correctIndex = 2,
            questionNumber = 47,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_047",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual propriedade da água é responsável pelo menisco em uma proveta?",
            answers = new string[] {
                "Coesão",
                "Adesão",
                "Tensão superficial",
                "Densidade"
            },
            correctIndex = 2,
            questionNumber = 48,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_048",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual o nome dado a uma substância com regiões hidrofóbicas e hidrofílicas?",
            answers = new string[] {
                "Anfipática",
                "Hidrofóbica",
                "Hidrofílica",
                "Polar"
            },
            correctIndex = 0,
            questionNumber = 49,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_049",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O que é uma micela?",
            answers = new string[] {
                "Um tipo de ligação covalente",
                "Um tipo de ligação de hidrogênio",
                "Um agregado de moléculas anfipáticas",
                "Um tipo de proteína"
            },
            correctIndex = 2,
            questionNumber = 50,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_050",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A molécula de água é formada por:",
            answers = new string[] {
                "Dois átomos de hidrogênio e um de oxigênio",
                "Dois átomos de oxigênio e um de hidrogênio",
                "Três átomos de oxigênio",
                "Dois átomos de hidrogênio apenas"
            },
            correctIndex = 0,
            questionNumber = 51,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_051",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A água é considerada uma molécula:",
            answers = new string[] {
                "Apolar",
                "Polar",
                "Neutra sem polaridade",
                "Somente iônica"
            },
            correctIndex = 1,
            questionNumber = 52,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_052",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A ligação que mantém os átomos de hidrogênio e oxigênio dentro da molécula de água é:",
            answers = new string[] {
                "Ligação de hidrogênio",
                "Ligação iônica",
                "Ligação covalente",
                "Ligação metálica"
            },
            correctIndex = 2,
            questionNumber = 53,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_053",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "As interações entre moléculas de água, responsáveis por suas propriedades especiais, são chamadas de:",
            answers = new string[] {
                "Ligações dissulfeto",
                "Ligações de hidrogênio",
                "Ligações peptídicas",
                "Ligações covalentes duplas"
            },
            correctIndex = 1,
            questionNumber = 54,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_054",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Em um paciente com desidratação intensa, qual função da água deve ser priorizada para explicar a queda no transporte de substâncias pelo corpo?",
            answers = new string[] {
                "Fonte primária de energia química.",
                "Meio solvente que permite circulação e transporte de solutos.",
                "Armazenamento direto de informação genética.",
                "Formação da estrutura primária de proteínas."
            },
            correctIndex = 1,
            questionNumber = 55,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_055",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A capacidade da água de dissolver muitas substâncias faz com que seja chamada de:",
            answers = new string[] {
                "Soluto universal",
                "Solvente universal",
                "Cofator biológico",
                "Enzima natural"
            },
            correctIndex = 1,
            questionNumber = 56,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_056",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A alta capacidade térmica da água permite que:",
            answers = new string[] {
                "O corpo humano mantenha a temperatura estável",
                "As proteínas sejam formadas mais rapidamente",
                "Os lipídeos se dissolvam facilmente",
                "O oxigênio seja transportado sem hemoglobina"
            },
            correctIndex = 0,
            questionNumber = 57,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_057",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O processo em que moléculas de água interagem entre si devido às ligações de hidrogênio é chamado de:",
            answers = new string[] {
                "Adesão",
                "Coesão",
                "Capilaridade",
                "Dissociação"
            },
            correctIndex = 1,
            questionNumber = 58,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_058",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O fenômeno da capilaridade ocorre porque a água apresenta:",
            answers = new string[] {
                "Apenas coesão",
                "Apenas adesão",
                "Coesão e adesão",
                "Nem coesão nem adesão"
            },
            correctIndex = 2,
            questionNumber = 59,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_059",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A densidade da água é maior em qual estado físico?",
            answers = new string[] {
                "Sólido (gelo)",
                "Líquido",
                "Gasoso",
                "Plasma"
            },
            correctIndex = 1,
            questionNumber = 60,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_060",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual explicação avalia melhor o papel da água em uma reação de hidrólise?",
            answers = new string[] {
                "A água fornece energia livre suficiente para qualquer reação ocorrer espontaneamente.",
                "A água participa como reagente, contribuindo para a quebra de ligações químicas.",
                "A água atua sempre como enzima principal da reação.",
                "A água impede a quebra de moléculas porque estabiliza todas as ligações."
            },
            correctIndex = 1,
            questionNumber = 61,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_061",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual é a porcentagem aproximada de água no corpo humano adulto?",
            answers = new string[] {
                "20%",
                "40%",
                "60%",
                "80%"
            },
            correctIndex = 2,
            questionNumber = 62,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_062",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A atração entre moléculas de água, que explica fenômenos como a tensão superficial, é devida a:",
            answers = new string[] {
                "Ligações covalentes",
                "Ligações de hidrogênio",
                "Ligações peptídicas",
                "Ligações glicosídicas"
            },
            correctIndex = 1,
            questionNumber = 63,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_063",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O calor específico elevado da água é importante porque:",
            answers = new string[] {
                "Permite que organismos mantenham a temperatura estável",
                "Reduz a evaporação nos rios",
                "Facilita o transporte de gases no sangue",
                "Torna a água uma boa fonte de energia"
            },
            correctIndex = 0,
            questionNumber = 64,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_064",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "O movimento da água através de uma membrana semipermeável é chamado:",
            answers = new string[] {
                "Difusão",
                "Osmose",
                "Transporte ativo",
                "Exocitose"
            },
            correctIndex = 1,
            questionNumber = 65,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_065",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Remember,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A densidade da água no estado sólido é menor que no líquido. Isso explica:",
            answers = new string[] {
                "A evaporação da água em baixas temperaturas",
                "O gelo flutuar na água",
                "A água ser polar",
                "O pH neutro da água"
            },
            correctIndex = 1,
            questionNumber = 66,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_066",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A função da água como reagente é observada em processos como:",
            answers = new string[] {
                "Respiração celular",
                "Hidrólise",
                "Fotossíntese",
                "Todas as alternativas anteriores"
            },
            correctIndex = 3,
            questionNumber = 67,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_067",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Understand,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A propriedade da água que permite a subida da seiva nas plantas pelo xilema é chamada:",
            answers = new string[] {
                "Difusão",
                "Evaporação",
                "Adesão e coesão",
                "Ionização"
            },
            correctIndex = 2,
            questionNumber = 68,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 1,
            questionInDevelopment = false,
            globalId = "water_068",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Apply,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "NaCl, óleo e glicose são adicionados separadamente à água. Qual análise compara melhor a solubilidade esperada dessas substâncias?",
            answers = new string[] {
                "NaCl e glicose tendem a interagir bem com água; óleo tende a ser pouco solúvel por ser majoritariamente apolar.",
                "Óleo é o mais solúvel porque moléculas apolares formam mais ligações de hidrogênio.",
                "Glicose é insolúvel porque possui muitos grupos hidroxila.",
                "NaCl não se dissolve porque íons não interagem com moléculas polares."
            },
            correctIndex = 0,
            questionNumber = 69,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/solute_comparison_nacl_oil_glucose",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_069",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Por que lagos tendem a congelar de cima para baixo, preservando água líquida abaixo da camada de gelo?",
            answers = new string[] {
                "Porque o gelo é menos denso que a água líquida e funciona como camada isolante superficial.",
                "Porque o gelo é mais denso que a água líquida e afunda rapidamente.",
                "Porque a água líquida não sofre variação de densidade com a temperatura.",
                "Porque ligações covalentes desaparecem quando a água congela."
            },
            correctIndex = 0,
            questionNumber = 70,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/lake_freezing_density_layers",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_070",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Água e álcool evaporam da pele. Qual análise explica por que ambos podem causar sensação de resfriamento?",
            answers = new string[] {
                "A evaporação absorve energia térmica da pele; a intensidade depende do calor de vaporização e da volatilidade.",
                "A evaporação libera calor diretamente sobre a pele.",
                "O resfriamento ocorre apenas se a substância for apolar.",
                "O resfriamento ocorre porque líquidos evaporados aumentam a temperatura corporal."
            },
            correctIndex = 0,
            questionNumber = 71,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_071",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Um gráfico mostra que a substância A precisa de mais energia que a substância B para aumentar 1°C. Qual conclusão é mais adequada?",
            answers = new string[] {
                "A substância A tem maior calor específico que B.",
                "A substância B tem maior calor específico que A.",
                "As duas substâncias têm o mesmo calor específico.",
                "A substância A necessariamente evapora mais rápido que B."
            },
            correctIndex = 0,
            questionNumber = 72,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/specific_heat_energy_graph",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_072",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Em um tubo fino, a água sobe pelas paredes internas. Qual análise integra corretamente os fenômenos envolvidos?",
            answers = new string[] {
                "A adesão atrai a água à parede do tubo e a coesão ajuda a puxar outras moléculas de água.",
                "A coesão repele a parede do tubo e impede a subida da água.",
                "A capilaridade depende apenas da densidade, sem participação de adesão ou coesão.",
                "A água sobe porque suas ligações covalentes se quebram no tubo."
            },
            correctIndex = 0,
            questionNumber = 73,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/capillary_action_tube",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_073",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual comparação entre micelas e bicamadas lipídicas está mais correta?",
            answers = new string[] {
                "Micelas geralmente têm uma camada de moléculas; bicamadas têm duas folhas com caudas hidrofóbicas voltadas para o interior.",
                "Micelas e bicamadas são idênticas em organização e função.",
                "Bicamadas colocam as caudas hidrofóbicas em contato direto com a água.",
                "Micelas são formadas por moléculas completamente apolares."
            },
            correctIndex = 0,
            questionNumber = 74,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/micelle_vs_bilayer",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_074",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Um aquário aquece de 20°C para 30°C mantendo a mesma pressão. Qual análise prevê melhor o efeito sobre o oxigênio dissolvido?",
            answers = new string[] {
                "A solubilidade do oxigênio tende a diminuir, podendo dificultar a respiração dos peixes.",
                "A solubilidade do oxigênio tende a aumentar muito, eliminando risco para os peixes.",
                "A temperatura não afeta a solubilidade de gases em água.",
                "O oxigênio se torna iônico e por isso deixa de dissolver."
            },
            correctIndex = 0,
            questionNumber = 75,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 2,
            questionInDevelopment = false,
            globalId = "water_075",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Analyze,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual explicação é mais convincente para a água dissolver sais como NaCl?",
            answers = new string[] {
                "A polaridade da água permite interações íon-dipolo que estabilizam íons separados em solução.",
                "A água quebra qualquer ligação covalente porque é um solvente universal absoluto.",
                "A água dissolve sais apenas por aumentar sua temperatura.",
                "A água dissolve sais porque suas moléculas são apolares."
            },
            correctIndex = 0,
            questionNumber = 76,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/nacl_dissolution_ion_dipole",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_076",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Um aluno diz que o suor resfria o corpo porque a água fria fica sobre a pele. Qual avaliação é mais adequada?",
            answers = new string[] {
                "A explicação é incompleta; o resfriamento principal ocorre porque a evaporação remove calor da pele.",
                "A explicação está completa; evaporação não participa do resfriamento.",
                "A explicação está errada porque suor sempre aquece o corpo.",
                "A explicação está correta apenas se o suor for apolar."
            },
            correctIndex = 0,
            questionNumber = 77,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_077",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Em um aquário com pouco oxigênio dissolvido, qual intervenção é melhor justificada pelas propriedades da água?",
            answers = new string[] {
                "Reduzir temperatura excessiva e aumentar aeração para favorecer entrada de O<sub><size=150%>2</size></sub>.",
                "Aquecer a água ao máximo para aumentar a solubilidade de gases.",
                "Adicionar óleo para aumentar a polaridade da água.",
                "Remover toda agitação para impedir contato com o ar."
            },
            correctIndex = 0,
            questionNumber = 78,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_078",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "A frase \"a água dissolve tudo\" aparece em um material didático. Qual avaliação é mais apropriada?",
            answers = new string[] {
                "É exagerada; a água dissolve muitas substâncias polares e iônicas, mas não dissolve bem substâncias apolares.",
                "É perfeita; qualquer substância se dissolve completamente em água.",
                "É falsa; água não dissolve substâncias iônicas.",
                "É correta apenas para lipídeos apolares."
            },
            correctIndex = 0,
            questionNumber = 79,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_079",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Em uma lâmina de vidro, a água forma um menisco côncavo. Qual julgamento explica melhor o fenômeno?",
            answers = new string[] {
                "A adesão entre água e vidro supera parcialmente a coesão entre moléculas de água nas bordas.",
                "A tensão superficial elimina a adesão, impedindo contato com o vidro.",
                "A densidade da água é a única causa do menisco.",
                "O menisco indica que a água se tornou apolar."
            },
            correctIndex = 0,
            questionNumber = 80,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/concave_meniscus_glass",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_080",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual propriedade da água é mais importante para evitar variações bruscas de temperatura em organismos?",
            answers = new string[] {
                "Alto calor específico, pois a água absorve ou libera bastante energia com pequena variação térmica.",
                "Baixa tensão superficial, pois reduz a perda de sais.",
                "Baixa polaridade, pois impede interações com solutos.",
                "Baixa densidade no estado líquido, pois aumenta a evaporação."
            },
            correctIndex = 0,
            questionNumber = 81,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_081",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Um estudante explica que o gelo flutua porque \"é mais frio\". Qual avaliação corrige melhor essa explicação?",
            answers = new string[] {
                "A temperatura não é a explicação central; o gelo flutua porque sua estrutura sólida é menos densa que a água líquida.",
                "A explicação está completa, pois qualquer material frio flutua.",
                "O gelo flutua porque é mais denso que a água líquida.",
                "O gelo flutua porque perde seus átomos de oxigênio."
            },
            correctIndex = 0,
            questionNumber = 82,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/ice_lattice_density",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_082",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Observando as estruturas de etanol, hexano, glicose e Na<sup><size=150%>+</size></sup>, qual opção provavelmente terá menor solubilidade em água?",
            answers = new string[] {
                "Hexano, por ser majoritariamente apolar.",
                "Glicose, por possuir muitos grupos hidroxila.",
                "Na<sup><size=150%>+</size></sup>, por interagir com o oxigênio da água.",
                "Etanol, por possuir grupo hidroxila."
            },
            correctIndex = 0,
            questionNumber = 83,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/solute_structures_ethanol_hexane_glucose_sodium",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_083",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual evidência experimental apoiaria melhor a existência de ligações de hidrogênio entre moléculas de água?",
            answers = new string[] {
                "Ponto de ebulição e calor de vaporização altos em comparação com moléculas semelhantes sem ligações de hidrogênio.",
                "Ausência total de evaporação em qualquer temperatura.",
                "Incapacidade da água de dissolver compostos iônicos.",
                "Massa molecular muito maior que a de qualquer outro líquido."
            },
            correctIndex = 0,
            questionNumber = 84,
            answerType = AnswerType.Text,
            questionType = QuestionType.Text,
            questionImagePath = "",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_084",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        },
        new Question
        {
            questionDatabankName = "WaterQuestionDatabase",
            questionText = "Qual modelo representa melhor fosfolipídios em água formando uma membrana?",
            answers = new string[] {
                "Cabeças hidrofílicas voltadas para a água e caudas hidrofóbicas voltadas para o interior da bicamada.",
                "Caudas hidrofóbicas voltadas para a água e cabeças escondidas no interior.",
                "Fosfolipídios isolados, sem interação entre si.",
                "Uma camada única com todas as regiões polares e apolares expostas igualmente à água."
            },
            correctIndex = 0,
            questionNumber = 85,
            answerType = AnswerType.Text,
            questionType = QuestionType.Image,
            questionImagePath = "QuestionImages/WaterDB/phospholipid_bilayer_models",
            questionLevel = 3,
            questionInDevelopment = false,
            globalId = "water_085",
            topic = "water",
            subtopic = null,
            displayName = "Água",
            bloomLevel = BloomLevel.Evaluate,
            conceptTags = null,
            prerequisites = null,
            questionHint = null
        }
    };

    public List<Question> GetQuestions() => questions;
    public QuestionSet GetQuestionSetType() => QuestionSet.water;
    public string GetDatabankName()  => "WaterQuestionDatabase";
    public string GetDisplayName()   => "Água";
    public bool IsDatabaseInDevelopment() => databaseInDevelopment;
}
